// Bulgarian vocabulary, transliterated to Latin letters.
// `bg` is the accepted answer (Latin), `cyr` is the Cyrillic (shown + spoken).
// A "/" in a value marks alternative accepted answers (e.g. "hand / arm").

export type Word = {
  en: string;
  bg: string; // Bulgarian written in Latin letters
  cyr: string; // Cyrillic, shown as a learning aid and used for speech
};

export type Theme = {
  id: string;
  name: string;
  emoji: string;
  hue: number; // base hue used for the theme's accent gradient
  words: Word[];
};

export const THEMES: Theme[] = [
  {
    id: "everyday",
    name: "Everyday phrases",
    emoji: "💬",
    hue: 265,
    words: [
      { en: "hello", bg: "zdravey", cyr: "здравей" },
      { en: "hi", bg: "zdrasti", cyr: "здрасти" },
      { en: "goodbye", bg: "dovizhdane", cyr: "довиждане" },
      { en: "thank you", bg: "blagodarya", cyr: "благодаря" },
      { en: "please", bg: "molya", cyr: "моля" },
      { en: "yes", bg: "da", cyr: "да" },
      { en: "no", bg: "ne", cyr: "не" },
      { en: "good morning", bg: "dobro utro", cyr: "добро утро" },
      { en: "good afternoon", bg: "dobar den", cyr: "добър ден" },
      { en: "good evening", bg: "dobar vecher", cyr: "добър вечер" },
      { en: "good night", bg: "leka nosht", cyr: "лека нощ" },
      { en: "how are you", bg: "kak si", cyr: "как си" },
      { en: "I'm fine", bg: "dobre sam", cyr: "добре съм" },
      { en: "excuse me", bg: "izvinete", cyr: "извинете" },
      { en: "sorry", bg: "sazhalyavam", cyr: "съжалявам" },
      { en: "behind us", bg: "zad nas", cyr: "зад нас" },
      { en: "I love you", bg: "obicham te", cyr: "обичам те" },
      { en: "what's your name", bg: "kak se kazvash", cyr: "как се казваш" },
      { en: "my name is", bg: "kazvam se", cyr: "казвам се" },
      { en: "where", bg: "kade", cyr: "къде" },
      { en: "when", bg: "koga", cyr: "кога" },
      { en: "why", bg: "zashto", cyr: "защо" },
      { en: "who", bg: "koy", cyr: "кой" },
      { en: "how", bg: "kak", cyr: "как" },
      { en: "how much", bg: "kolko", cyr: "колко" },
      { en: "now", bg: "sega", cyr: "сега" },
      { en: "of course", bg: "razbira se", cyr: "разбира се" },
      { en: "I don't know", bg: "ne znam", cyr: "не знам" },
      { en: "I don't understand", bg: "ne razbiram", cyr: "не разбирам" },
      { en: "help", bg: "pomosht", cyr: "помощ" },
      { en: "cheers", bg: "nazdrave", cyr: "наздраве" },
    ],
  },
  {
    id: "food",
    name: "Food & drink",
    emoji: "🍽️",
    hue: 12,
    words: [
      { en: "water", bg: "voda", cyr: "вода" },
      { en: "bread", bg: "hlyab", cyr: "хляб" },
      { en: "coffee", bg: "kafe", cyr: "кафе" },
      { en: "beer", bg: "bira", cyr: "бира" },
      { en: "wine", bg: "vino", cyr: "вино" },
      { en: "milk", bg: "mlyako", cyr: "мляко" },
      { en: "cheese", bg: "sirene", cyr: "сирене" },
      { en: "yellow cheese", bg: "kashkaval", cyr: "кашкавал" },
      { en: "meat", bg: "meso", cyr: "месо" },
      { en: "chicken", bg: "pile", cyr: "пиле" },
      { en: "fish", bg: "riba", cyr: "риба" },
      { en: "egg", bg: "yaytse", cyr: "яйце" },
      { en: "apple", bg: "yabalka", cyr: "ябълка" },
      { en: "banana", bg: "banan", cyr: "банан" },
      { en: "tomato", bg: "domat", cyr: "домат" },
      { en: "cucumber", bg: "krastavitsa", cyr: "краставица" },
      { en: "potato", bg: "kartof", cyr: "картоф" },
      { en: "soup", bg: "supa", cyr: "супа" },
      { en: "salad", bg: "salata", cyr: "салата" },
      { en: "sugar", bg: "zahar", cyr: "захар" },
      { en: "salt", bg: "sol", cyr: "сол" },
      { en: "pepper", bg: "piper", cyr: "пипер" },
      { en: "tea", bg: "chay", cyr: "чай" },
      { en: "juice", bg: "sok", cyr: "сок" },
      { en: "yogurt", bg: "kiselo mlyako", cyr: "кисело мляко" },
      { en: "breakfast", bg: "zakuska", cyr: "закуска" },
      { en: "lunch", bg: "obyad", cyr: "обяд" },
      { en: "dinner", bg: "vecherya", cyr: "вечеря" },
      { en: "the bill", bg: "smetkata", cyr: "сметката" },
      { en: "delicious", bg: "vkusno", cyr: "вкусно" },
      { en: "spicy", bg: "lyuto", cyr: "люто" },
    ],
  },
  {
    id: "travel",
    name: "Travel & places",
    emoji: "✈️",
    hue: 192,
    words: [
      { en: "airport", bg: "letishte", cyr: "летище" },
      { en: "train", bg: "vlak", cyr: "влак" },
      { en: "bus", bg: "avtobus", cyr: "автобус" },
      { en: "car", bg: "kola", cyr: "кола" },
      { en: "taxi", bg: "taksi", cyr: "такси" },
      { en: "ticket", bg: "bilet", cyr: "билет" },
      { en: "hotel", bg: "hotel", cyr: "хотел" },
      { en: "room", bg: "staya", cyr: "стая" },
      { en: "street", bg: "ulitsa", cyr: "улица" },
      { en: "square", bg: "ploshtad", cyr: "площад" },
      { en: "city", bg: "grad", cyr: "град" },
      { en: "village", bg: "selo", cyr: "село" },
      { en: "left", bg: "lyavo", cyr: "ляво" },
      { en: "right", bg: "dyasno", cyr: "дясно" },
      { en: "straight ahead", bg: "napravo", cyr: "направо" },
      { en: "near", bg: "blizo", cyr: "близо" },
      { en: "far", bg: "daleche", cyr: "далече" },
      { en: "map", bg: "karta", cyr: "карта" },
      { en: "beach", bg: "plazh", cyr: "плаж" },
      { en: "sea", bg: "more", cyr: "море" },
      { en: "mountain", bg: "planina", cyr: "планина" },
      { en: "river", bg: "reka", cyr: "река" },
      { en: "forest", bg: "gora", cyr: "гора" },
      { en: "park", bg: "park", cyr: "парк" },
      { en: "church", bg: "tsarkva", cyr: "църква" },
      { en: "museum", bg: "muzey", cyr: "музей" },
      { en: "market", bg: "pazar", cyr: "пазар" },
      { en: "station", bg: "gara", cyr: "гара" },
      { en: "where is", bg: "kade e", cyr: "къде е" },
      { en: "passport", bg: "pasport", cyr: "паспорт" },
      { en: "luggage", bg: "bagazh", cyr: "багаж" },
    ],
  },
  {
    id: "numbers",
    name: "Numbers & time",
    emoji: "🔢",
    hue: 142,
    words: [
      { en: "zero", bg: "nula", cyr: "нула" },
      { en: "one", bg: "edno", cyr: "едно" },
      { en: "two", bg: "dve", cyr: "две" },
      { en: "three", bg: "tri", cyr: "три" },
      { en: "four", bg: "chetiri", cyr: "четири" },
      { en: "five", bg: "pet", cyr: "пет" },
      { en: "six", bg: "shest", cyr: "шест" },
      { en: "seven", bg: "sedem", cyr: "седем" },
      { en: "eight", bg: "osem", cyr: "осем" },
      { en: "nine", bg: "devet", cyr: "девет" },
      { en: "ten", bg: "deset", cyr: "десет" },
      { en: "eleven", bg: "edinadeset", cyr: "единадесет" },
      { en: "twelve", bg: "dvanadeset", cyr: "дванадесет" },
      { en: "twenty", bg: "dvadeset", cyr: "двадесет" },
      { en: "fifty", bg: "petdeset", cyr: "петдесет" },
      { en: "hundred", bg: "sto", cyr: "сто" },
      { en: "thousand", bg: "hilyada", cyr: "хиляда" },
      { en: "today", bg: "dnes", cyr: "днес" },
      { en: "tomorrow", bg: "utre", cyr: "утре" },
      { en: "yesterday", bg: "vchera", cyr: "вчера" },
      { en: "day", bg: "den", cyr: "ден" },
      { en: "week", bg: "sedmitsa", cyr: "седмица" },
      { en: "month", bg: "mesets", cyr: "месец" },
      { en: "year", bg: "godina", cyr: "година" },
      { en: "hour", bg: "chas", cyr: "час" },
      { en: "minute", bg: "minuta", cyr: "минута" },
      { en: "morning", bg: "sutrin", cyr: "сутрин" },
      { en: "evening", bg: "vecher", cyr: "вечер" },
      { en: "Monday", bg: "ponedelnik", cyr: "понеделник" },
      { en: "Friday", bg: "petak", cyr: "петък" },
      { en: "what time is it", bg: "kolko e chasat", cyr: "колко е часът" },
    ],
  },
  {
    id: "family",
    name: "Family & people",
    emoji: "👪",
    hue: 320,
    words: [
      { en: "mother", bg: "mayka", cyr: "майка" },
      { en: "father", bg: "bashta", cyr: "баща" },
      { en: "parents", bg: "roditeli", cyr: "родители" },
      { en: "son", bg: "sin", cyr: "син" },
      { en: "daughter", bg: "dashterya", cyr: "дъщеря" },
      { en: "child", bg: "dete", cyr: "дете" },
      { en: "children", bg: "detsa", cyr: "деца" },
      { en: "brother", bg: "brat", cyr: "брат" },
      { en: "sister", bg: "sestra", cyr: "сестра" },
      { en: "grandmother", bg: "baba", cyr: "баба" },
      { en: "grandfather", bg: "dyado", cyr: "дядо" },
      { en: "husband", bg: "saprug", cyr: "съпруг" },
      { en: "wife", bg: "sapruga", cyr: "съпруга" },
      { en: "friend", bg: "priyatel", cyr: "приятел" },
      { en: "girlfriend", bg: "priyatelka", cyr: "приятелка" },
      { en: "boy", bg: "momche", cyr: "момче" },
      { en: "girl", bg: "momiche", cyr: "момиче" },
      { en: "man", bg: "mazh", cyr: "мъж" },
      { en: "woman", bg: "zhena", cyr: "жена" },
      { en: "people", bg: "hora", cyr: "хора" },
      { en: "family", bg: "semeystvo", cyr: "семейство" },
      { en: "name", bg: "ime", cyr: "име" },
      { en: "neighbor", bg: "sased", cyr: "съсед" },
      { en: "guest", bg: "gost", cyr: "гост" },
    ],
  },
  {
    id: "body",
    name: "Body & health",
    emoji: "🩺",
    hue: 0,
    words: [
      { en: "head", bg: "glava", cyr: "глава" },
      { en: "hair", bg: "kosa", cyr: "коса" },
      { en: "eye", bg: "oko", cyr: "око" },
      { en: "eyes", bg: "ochi", cyr: "очи" },
      { en: "ear", bg: "uho", cyr: "ухо" },
      { en: "nose", bg: "nos", cyr: "нос" },
      { en: "mouth", bg: "usta", cyr: "уста" },
      { en: "tooth", bg: "zab", cyr: "зъб" },
      { en: "tongue", bg: "ezik", cyr: "език" },
      { en: "neck", bg: "vrat", cyr: "врат" },
      { en: "hand / arm", bg: "raka", cyr: "ръка" },
      { en: "finger", bg: "prast", cyr: "пръст" },
      { en: "leg / foot", bg: "krak", cyr: "крак" },
      { en: "heart", bg: "sartse", cyr: "сърце" },
      { en: "stomach", bg: "stomah", cyr: "стомах" },
      { en: "back", bg: "garb", cyr: "гръб" },
      { en: "blood", bg: "krav", cyr: "кръв" },
      { en: "skin", bg: "kozha", cyr: "кожа" },
      { en: "doctor", bg: "lekar", cyr: "лекар" },
      { en: "pharmacy", bg: "apteka", cyr: "аптека" },
      { en: "medicine", bg: "lekarstvo", cyr: "лекарство" },
      { en: "pain", bg: "bolka", cyr: "болка" },
      { en: "sick", bg: "bolen", cyr: "болен" },
      { en: "healthy", bg: "zdrav", cyr: "здрав" },
      { en: "hospital", bg: "bolnitsa", cyr: "болница" },
    ],
  },
  {
    id: "weather",
    name: "Weather & nature",
    emoji: "🌦️",
    hue: 205,
    words: [
      { en: "weather", bg: "vreme", cyr: "време" },
      { en: "sun", bg: "slantse", cyr: "слънце" },
      { en: "moon", bg: "luna", cyr: "луна" },
      { en: "star", bg: "zvezda", cyr: "звезда" },
      { en: "sky", bg: "nebe", cyr: "небе" },
      { en: "cloud", bg: "oblak", cyr: "облак" },
      { en: "rain", bg: "dazhd", cyr: "дъжд" },
      { en: "snow", bg: "snyag", cyr: "сняг" },
      { en: "wind", bg: "vyatar", cyr: "вятър" },
      { en: "storm", bg: "burya", cyr: "буря" },
      { en: "fog", bg: "magla", cyr: "мъгла" },
      { en: "hot", bg: "goreshto", cyr: "горещо" },
      { en: "cold", bg: "studeno", cyr: "студено" },
      { en: "warm", bg: "toplo", cyr: "топло" },
      { en: "ice", bg: "led", cyr: "лед" },
      { en: "fire", bg: "ogan", cyr: "огън" },
      { en: "earth", bg: "zemya", cyr: "земя" },
      { en: "tree", bg: "darvo", cyr: "дърво" },
      { en: "flower", bg: "tsvete", cyr: "цвете" },
      { en: "grass", bg: "treva", cyr: "трева" },
      { en: "animal", bg: "zhivotno", cyr: "животно" },
      { en: "spring", bg: "prolet", cyr: "пролет" },
      { en: "summer", bg: "lyato", cyr: "лято" },
      { en: "autumn", bg: "esen", cyr: "есен" },
      { en: "winter", bg: "zima", cyr: "зима" },
    ],
  },
  {
    id: "shopping",
    name: "Shopping & money",
    emoji: "🛍️",
    hue: 45,
    words: [
      { en: "shop", bg: "magazin", cyr: "магазин" },
      { en: "market", bg: "pazar", cyr: "пазар" },
      { en: "money", bg: "pari", cyr: "пари" },
      { en: "price", bg: "tsena", cyr: "цена" },
      { en: "cheap", bg: "evtino", cyr: "евтино" },
      { en: "expensive", bg: "skapo", cyr: "скъпо" },
      { en: "how much does it cost", bg: "kolko struva", cyr: "колко струва" },
      { en: "to buy", bg: "kupuvam", cyr: "купувам" },
      { en: "to pay", bg: "plashtam", cyr: "плащам" },
      { en: "to sell", bg: "prodavam", cyr: "продавам" },
      { en: "cash", bg: "v broy", cyr: "в брой" },
      { en: "receipt", bg: "kasova belezhka", cyr: "касова бележка" },
      { en: "bag", bg: "torba", cyr: "торба" },
      { en: "clothes", bg: "drehi", cyr: "дрехи" },
      { en: "shoes", bg: "obuvki", cyr: "обувки" },
      { en: "shirt", bg: "riza", cyr: "риза" },
      { en: "trousers", bg: "pantalon", cyr: "панталон" },
      { en: "dress", bg: "roklya", cyr: "рокля" },
      { en: "hat", bg: "shapka", cyr: "шапка" },
      { en: "size", bg: "razmer", cyr: "размер" },
      { en: "open", bg: "otvoreno", cyr: "отворено" },
      { en: "closed", bg: "zatvoreno", cyr: "затворено" },
      { en: "sale", bg: "namalenie", cyr: "намаление" },
      { en: "gift", bg: "podarak", cyr: "подарък" },
    ],
  },
  {
    id: "verbs",
    name: "Common verbs",
    emoji: "🏃",
    hue: 160,
    words: [
      { en: "to be", bg: "sam", cyr: "съм" },
      { en: "to have", bg: "imam", cyr: "имам" },
      { en: "to want", bg: "iskam", cyr: "искам" },
      { en: "to be able", bg: "moga", cyr: "мога" },
      { en: "to go", bg: "otivam", cyr: "отивам" },
      { en: "to come", bg: "idvam", cyr: "идвам" },
      { en: "to eat", bg: "yam", cyr: "ям" },
      { en: "to drink", bg: "piya", cyr: "пия" },
      { en: "to sleep", bg: "spya", cyr: "спя" },
      { en: "to speak", bg: "govorya", cyr: "говоря" },
      { en: "to know", bg: "znam", cyr: "знам" },
      { en: "to see", bg: "vizhdam", cyr: "виждам" },
      { en: "to make / do", bg: "pravya", cyr: "правя" },
      { en: "to give", bg: "davam", cyr: "давам" },
      { en: "to take", bg: "vzemam", cyr: "взимам" },
      { en: "to read", bg: "cheta", cyr: "чета" },
      { en: "to write", bg: "pisha", cyr: "пиша" },
      { en: "to work", bg: "rabotya", cyr: "работя" },
      { en: "to live", bg: "zhiveya", cyr: "живея" },
      { en: "to love", bg: "obicham", cyr: "обичам" },
      { en: "to think", bg: "mislya", cyr: "мисля" },
      { en: "to open", bg: "otvaryam", cyr: "отварям" },
      { en: "to wait", bg: "chakam", cyr: "чакам" },
      { en: "to walk", bg: "varvya", cyr: "вървя" },
      { en: "to run", bg: "byagam", cyr: "бягам" },
      { en: "to help", bg: "pomagam", cyr: "помагам" },
    ],
  },
  {
    id: "colors",
    name: "Colors & shapes",
    emoji: "🎨",
    hue: 285,
    words: [
      { en: "color", bg: "tsvyat", cyr: "цвят" },
      { en: "red", bg: "cherveno", cyr: "червено" },
      { en: "blue", bg: "sinyo", cyr: "синьо" },
      { en: "green", bg: "zeleno", cyr: "зелено" },
      { en: "yellow", bg: "zhalto", cyr: "жълто" },
      { en: "white", bg: "byalo", cyr: "бяло" },
      { en: "black", bg: "cherno", cyr: "черно" },
      { en: "orange", bg: "oranzhevo", cyr: "оранжево" },
      { en: "purple", bg: "lilavo", cyr: "лилаво" },
      { en: "pink", bg: "rozovo", cyr: "розово" },
      { en: "brown", bg: "kafyavo", cyr: "кафяво" },
      { en: "grey", bg: "sivo", cyr: "сиво" },
      { en: "gold", bg: "zlatno", cyr: "златно" },
      { en: "silver", bg: "srebarno", cyr: "сребърно" },
      { en: "light", bg: "svetlo", cyr: "светло" },
      { en: "dark", bg: "tamno", cyr: "тъмно" },
      { en: "circle", bg: "krag", cyr: "кръг" },
      { en: "square", bg: "kvadrat", cyr: "квадрат" },
      { en: "triangle", bg: "triagalnik", cyr: "триъгълник" },
      { en: "line", bg: "liniya", cyr: "линия" },
      { en: "dot", bg: "tochka", cyr: "точка" },
      { en: "round", bg: "kragal", cyr: "кръгъл" },
      { en: "big", bg: "golyam", cyr: "голям" },
      { en: "small", bg: "malak", cyr: "малък" },
      { en: "bright", bg: "yarak", cyr: "ярък" },
      { en: "shape", bg: "forma", cyr: "форма" },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    emoji: "🐾",
    hue: 35,
    words: [
      { en: "animal", bg: "zhivotno", cyr: "животно" },
      { en: "dog", bg: "kuche", cyr: "куче" },
      { en: "cat", bg: "kotka", cyr: "котка" },
      { en: "horse", bg: "kon", cyr: "кон" },
      { en: "cow", bg: "krava", cyr: "крава" },
      { en: "pig", bg: "svinya", cyr: "свиня" },
      { en: "sheep", bg: "ovtsa", cyr: "овца" },
      { en: "goat", bg: "koza", cyr: "коза" },
      { en: "hen", bg: "kokoshka", cyr: "кокошка" },
      { en: "rooster", bg: "petel", cyr: "петел" },
      { en: "duck", bg: "patitsa", cyr: "патица" },
      { en: "bird", bg: "ptitsa", cyr: "птица" },
      { en: "rabbit", bg: "zaek", cyr: "заек" },
      { en: "mouse", bg: "mishka", cyr: "мишка" },
      { en: "bear", bg: "mechka", cyr: "мечка" },
      { en: "wolf", bg: "valk", cyr: "вълк" },
      { en: "fox", bg: "lisitsa", cyr: "лисица" },
      { en: "lion", bg: "lav", cyr: "лъв" },
      { en: "elephant", bg: "slon", cyr: "слон" },
      { en: "monkey", bg: "maymuna", cyr: "маймуна" },
      { en: "snake", bg: "zmiya", cyr: "змия" },
      { en: "frog", bg: "zhaba", cyr: "жаба" },
      { en: "bee", bg: "pchela", cyr: "пчела" },
      { en: "spider", bg: "payak", cyr: "паяк" },
      { en: "butterfly", bg: "peperuda", cyr: "пеперуда" },
      { en: "turtle", bg: "kostenurka", cyr: "костенурка" },
      { en: "deer", bg: "elen", cyr: "елен" },
    ],
  },
  {
    id: "home",
    name: "House & home",
    emoji: "🏠",
    hue: 172,
    words: [
      { en: "house", bg: "kashta", cyr: "къща" },
      { en: "home", bg: "dom", cyr: "дом" },
      { en: "door", bg: "vrata", cyr: "врата" },
      { en: "window", bg: "prozorets", cyr: "прозорец" },
      { en: "wall", bg: "stena", cyr: "стена" },
      { en: "floor", bg: "pod", cyr: "под" },
      { en: "ceiling", bg: "tavan", cyr: "таван" },
      { en: "roof", bg: "pokriv", cyr: "покрив" },
      { en: "room", bg: "staya", cyr: "стая" },
      { en: "kitchen", bg: "kuhnya", cyr: "кухня" },
      { en: "bedroom", bg: "spalnya", cyr: "спалня" },
      { en: "bathroom", bg: "banya", cyr: "баня" },
      { en: "table", bg: "masa", cyr: "маса" },
      { en: "chair", bg: "stol", cyr: "стол" },
      { en: "bed", bg: "leglo", cyr: "легло" },
      { en: "sofa", bg: "divan", cyr: "диван" },
      { en: "key", bg: "klyuch", cyr: "ключ" },
      { en: "lamp", bg: "lampa", cyr: "лампа" },
      { en: "mirror", bg: "ogledalo", cyr: "огледало" },
      { en: "shelf", bg: "raft", cyr: "рафт" },
      { en: "cupboard", bg: "shkaf", cyr: "шкаф" },
      { en: "carpet", bg: "kilim", cyr: "килим" },
      { en: "stairs", bg: "stalbi", cyr: "стълби" },
      { en: "garden", bg: "gradina", cyr: "градина" },
      { en: "yard", bg: "dvor", cyr: "двор" },
      { en: "garage", bg: "garazh", cyr: "гараж" },
      { en: "television", bg: "televizor", cyr: "телевизор" },
      { en: "fridge", bg: "hladilnik", cyr: "хладилник" },
    ],
  },
  {
    id: "jobs",
    name: "Jobs & professions",
    emoji: "💼",
    hue: 222,
    words: [
      { en: "work / job", bg: "rabota", cyr: "работа" },
      { en: "teacher", bg: "uchitel", cyr: "учител" },
      { en: "student", bg: "student", cyr: "студент" },
      { en: "doctor", bg: "lekar", cyr: "лекар" },
      { en: "nurse", bg: "meditsinska sestra", cyr: "медицинска сестра" },
      { en: "engineer", bg: "inzhener", cyr: "инженер" },
      { en: "lawyer", bg: "advokat", cyr: "адвокат" },
      { en: "police officer", bg: "politsay", cyr: "полицай" },
      { en: "firefighter", bg: "pozharnikar", cyr: "пожарникар" },
      { en: "cook / chef", bg: "gotvach", cyr: "готвач" },
      { en: "waiter", bg: "servityor", cyr: "сервитьор" },
      { en: "driver", bg: "shofyor", cyr: "шофьор" },
      { en: "farmer", bg: "fermer", cyr: "фермер" },
      { en: "builder", bg: "stroitel", cyr: "строител" },
      { en: "writer", bg: "pisatel", cyr: "писател" },
      { en: "artist", bg: "hudozhnik", cyr: "художник" },
      { en: "musician", bg: "muzikant", cyr: "музикант" },
      { en: "actor", bg: "aktyor", cyr: "актьор" },
      { en: "singer", bg: "pevets", cyr: "певец" },
      { en: "scientist", bg: "uchen", cyr: "учен" },
      { en: "programmer", bg: "programist", cyr: "програмист" },
      { en: "salesperson", bg: "prodavach", cyr: "продавач" },
      { en: "manager", bg: "menidzhar", cyr: "мениджър" },
      { en: "boss", bg: "shef", cyr: "шеф" },
      { en: "worker", bg: "rabotnik", cyr: "работник" },
      { en: "pilot", bg: "pilot", cyr: "пилот" },
      { en: "soldier", bg: "voynik", cyr: "войник" },
    ],
  },
  {
    id: "tech",
    name: "Technology & phone",
    emoji: "📱",
    hue: 200,
    words: [
      { en: "phone", bg: "telefon", cyr: "телефон" },
      { en: "computer", bg: "kompyutar", cyr: "компютър" },
      { en: "laptop", bg: "laptop", cyr: "лаптоп" },
      { en: "screen", bg: "ekran", cyr: "екран" },
      { en: "keyboard", bg: "klaviatura", cyr: "клавиатура" },
      { en: "mouse", bg: "mishka", cyr: "мишка" },
      { en: "internet", bg: "internet", cyr: "интернет" },
      { en: "email", bg: "imeyl", cyr: "имейл" },
      { en: "message", bg: "saobshtenie", cyr: "съобщение" },
      { en: "password", bg: "parola", cyr: "парола" },
      { en: "file", bg: "fayl", cyr: "файл" },
      { en: "app", bg: "prilozhenie", cyr: "приложение" },
      { en: "battery", bg: "bateriya", cyr: "батерия" },
      { en: "charger", bg: "zaryadno", cyr: "зарядно" },
      { en: "camera", bg: "kamera", cyr: "камера" },
      { en: "photo", bg: "snimka", cyr: "снимка" },
      { en: "video", bg: "video", cyr: "видео" },
      { en: "button", bg: "kopche", cyr: "копче" },
      { en: "network", bg: "mrezha", cyr: "мрежа" },
      { en: "signal", bg: "signal", cyr: "сигнал" },
      { en: "to call", bg: "obazhdam se", cyr: "обаждам се" },
      { en: "to download", bg: "svalyam", cyr: "свалям" },
      { en: "to click", bg: "klikam", cyr: "кликам" },
      { en: "smartphone", bg: "smartfon", cyr: "смартфон" },
      { en: "to charge", bg: "zarezhdam", cyr: "зареждам" },
      { en: "headphones", bg: "slushalki", cyr: "слушалки" },
    ],
  },
  {
    id: "emotions",
    name: "Emotions & feelings",
    emoji: "😊",
    hue: 350,
    words: [
      { en: "happy", bg: "shtastliv", cyr: "щастлив" },
      { en: "sad", bg: "tazhen", cyr: "тъжен" },
      { en: "angry", bg: "yadosan", cyr: "ядосан" },
      { en: "afraid", bg: "uplashen", cyr: "уплашен" },
      { en: "tired", bg: "umoren", cyr: "уморен" },
      { en: "bored", bg: "otegchen", cyr: "отегчен" },
      { en: "surprised", bg: "iznenadan", cyr: "изненадан" },
      { en: "excited", bg: "razvalnuvan", cyr: "развълнуван" },
      { en: "calm", bg: "spokoen", cyr: "спокоен" },
      { en: "nervous", bg: "nervozen", cyr: "нервозен" },
      { en: "proud", bg: "gord", cyr: "горд" },
      { en: "shy", bg: "sramezhliv", cyr: "срамежлив" },
      { en: "jealous", bg: "revniv", cyr: "ревнив" },
      { en: "lonely", bg: "samoten", cyr: "самотен" },
      { en: "confused", bg: "obarkan", cyr: "объркан" },
      { en: "love", bg: "lyubov", cyr: "любов" },
      { en: "fear", bg: "strah", cyr: "страх" },
      { en: "joy", bg: "radost", cyr: "радост" },
      { en: "anger", bg: "gnyav", cyr: "гняв" },
      { en: "hope", bg: "nadezhda", cyr: "надежда" },
      { en: "feeling", bg: "chuvstvo", cyr: "чувство" },
      { en: "to feel", bg: "chuvstvam", cyr: "чувствам" },
      { en: "to laugh", bg: "smeya se", cyr: "смея се" },
      { en: "to cry", bg: "placha", cyr: "плача" },
      { en: "to smile", bg: "usmihvam se", cyr: "усмихвам се" },
      { en: "glad", bg: "dovolen", cyr: "доволен" },
      { en: "hungry", bg: "gladen", cyr: "гладен" },
      { en: "thirsty", bg: "zhaden", cyr: "жаден" },
    ],
  },
  {
    id: "adjectives",
    name: "Adjectives",
    emoji: "✨",
    hue: 95,
    words: [
      { en: "good", bg: "dobar", cyr: "добър" },
      { en: "bad", bg: "losh", cyr: "лош" },
      { en: "new", bg: "nov", cyr: "нов" },
      { en: "old", bg: "star", cyr: "стар" },
      { en: "young", bg: "mlad", cyr: "млад" },
      { en: "hot", bg: "goresht", cyr: "горещ" },
      { en: "cold", bg: "studen", cyr: "студен" },
      { en: "fast", bg: "barz", cyr: "бърз" },
      { en: "slow", bg: "baven", cyr: "бавен" },
      { en: "easy", bg: "lesen", cyr: "лесен" },
      { en: "hard / difficult", bg: "truden", cyr: "труден" },
      { en: "beautiful", bg: "krasiv", cyr: "красив" },
      { en: "ugly", bg: "grozen", cyr: "грозен" },
      { en: "strong", bg: "silen", cyr: "силен" },
      { en: "weak", bg: "slab", cyr: "слаб" },
      { en: "rich", bg: "bogat", cyr: "богат" },
      { en: "poor", bg: "beden", cyr: "беден" },
      { en: "clean", bg: "chist", cyr: "чист" },
      { en: "dirty", bg: "mrasen", cyr: "мръсен" },
      { en: "full", bg: "palen", cyr: "пълен" },
      { en: "empty", bg: "prazen", cyr: "празен" },
      { en: "long", bg: "dalag", cyr: "дълъг" },
      { en: "short", bg: "kas", cyr: "къс" },
      { en: "tall / high", bg: "visok", cyr: "висок" },
      { en: "low", bg: "nisak", cyr: "нисък" },
      { en: "expensive", bg: "skap", cyr: "скъп" },
      { en: "important", bg: "vazhen", cyr: "важен" },
      { en: "wide", bg: "shirok", cyr: "широк" },
    ],
  },
  {
    id: "sports",
    name: "Sports & hobbies",
    emoji: "⚽",
    hue: 128,
    words: [
      { en: "sport", bg: "sport", cyr: "спорт" },
      { en: "game", bg: "igra", cyr: "игра" },
      { en: "ball", bg: "topka", cyr: "топка" },
      { en: "football", bg: "futbol", cyr: "футбол" },
      { en: "basketball", bg: "basketbol", cyr: "баскетбол" },
      { en: "tennis", bg: "tenis", cyr: "тенис" },
      { en: "to play", bg: "igraya", cyr: "играя" },
      { en: "to swim", bg: "pluvam", cyr: "плувам" },
      { en: "to jump", bg: "skacham", cyr: "скачам" },
      { en: "to dance", bg: "tantsuvam", cyr: "танцувам" },
      { en: "to sing", bg: "peya", cyr: "пея" },
      { en: "music", bg: "muzika", cyr: "музика" },
      { en: "film / movie", bg: "film", cyr: "филм" },
      { en: "hobby", bg: "hobi", cyr: "хоби" },
      { en: "to draw", bg: "risuvam", cyr: "рисувам" },
      { en: "team", bg: "otbor", cyr: "отбор" },
      { en: "player", bg: "igrach", cyr: "играч" },
      { en: "winner", bg: "pobeditel", cyr: "победител" },
      { en: "to win", bg: "pechelya", cyr: "печеля" },
      { en: "to lose", bg: "gubya", cyr: "губя" },
      { en: "gym", bg: "fitnes", cyr: "фитнес" },
      { en: "bicycle", bg: "kolelo", cyr: "колело" },
      { en: "to ride a bike", bg: "karam kolelo", cyr: "карам колело" },
      { en: "chess", bg: "shah", cyr: "шах" },
      { en: "guitar", bg: "kitara", cyr: "китара" },
      { en: "ski", bg: "ski", cyr: "ски" },
    ],
  },
  {
    id: "school",
    name: "School & education",
    emoji: "🎓",
    hue: 52,
    words: [
      { en: "school", bg: "uchilishte", cyr: "училище" },
      { en: "university", bg: "universitet", cyr: "университет" },
      { en: "lesson", bg: "urok", cyr: "урок" },
      { en: "pupil", bg: "uchenik", cyr: "ученик" },
      { en: "notebook", bg: "tetradka", cyr: "тетрадка" },
      { en: "pen", bg: "himikalka", cyr: "химикалка" },
      { en: "pencil", bg: "moliv", cyr: "молив" },
      { en: "paper", bg: "hartiya", cyr: "хартия" },
      { en: "desk", bg: "chin", cyr: "чин" },
      { en: "board", bg: "daska", cyr: "дъска" },
      { en: "homework", bg: "domashno", cyr: "домашно" },
      { en: "exam", bg: "izpit", cyr: "изпит" },
      { en: "test", bg: "test", cyr: "тест" },
      { en: "grade / mark", bg: "otsenka", cyr: "оценка" },
      { en: "question", bg: "vapros", cyr: "въпрос" },
      { en: "answer", bg: "otgovor", cyr: "отговор" },
      { en: "word", bg: "duma", cyr: "дума" },
      { en: "letter", bg: "bukva", cyr: "буква" },
      { en: "number", bg: "chislo", cyr: "число" },
      { en: "to learn", bg: "ucha", cyr: "уча" },
      { en: "to teach", bg: "prepodavam", cyr: "преподавам" },
      { en: "knowledge", bg: "znanie", cyr: "знание" },
      { en: "library", bg: "biblioteka", cyr: "библиотека" },
      { en: "dictionary", bg: "rechnik", cyr: "речник" },
      { en: "alphabet", bg: "azbuka", cyr: "азбука" },
      { en: "language", bg: "ezik", cyr: "език" },
      { en: "book", bg: "kniga", cyr: "книга" },
    ],
  },
  {
    id: "kitchen",
    name: "Kitchen & cooking",
    emoji: "🍳",
    hue: 18,
    words: [
      { en: "kitchen", bg: "kuhnya", cyr: "кухня" },
      { en: "plate", bg: "chiniya", cyr: "чиния" },
      { en: "bowl", bg: "kupa", cyr: "купа" },
      { en: "cup", bg: "chasha", cyr: "чаша" },
      { en: "spoon", bg: "lazhitsa", cyr: "лъжица" },
      { en: "fork", bg: "vilitsa", cyr: "вилица" },
      { en: "knife", bg: "nozh", cyr: "нож" },
      { en: "pot", bg: "tendzhera", cyr: "тенджера" },
      { en: "pan", bg: "tigan", cyr: "тиган" },
      { en: "oven", bg: "furna", cyr: "фурна" },
      { en: "stove", bg: "pechka", cyr: "печка" },
      { en: "to cook", bg: "gotvya", cyr: "готвя" },
      { en: "to bake", bg: "peka", cyr: "пека" },
      { en: "to fry", bg: "parzha", cyr: "пържа" },
      { en: "to boil", bg: "varya", cyr: "варя" },
      { en: "to cut", bg: "rezha", cyr: "режа" },
      { en: "to add", bg: "dobavyam", cyr: "добавям" },
      { en: "recipe", bg: "retsepta", cyr: "рецепта" },
      { en: "ingredient", bg: "sastavka", cyr: "съставка" },
      { en: "flour", bg: "brashno", cyr: "брашно" },
      { en: "oil", bg: "olio", cyr: "олио" },
      { en: "butter", bg: "maslo", cyr: "масло" },
      { en: "rice", bg: "oriz", cyr: "ориз" },
      { en: "pasta", bg: "makaroni", cyr: "макарони" },
      { en: "to taste", bg: "opitvam", cyr: "опитвам" },
      { en: "napkin", bg: "salfetka", cyr: "салфетка" },
      { en: "towel", bg: "karpa", cyr: "кърпа" },
    ],
  },
  {
    id: "city",
    name: "City & buildings",
    emoji: "🏙️",
    hue: 210,
    words: [
      { en: "city", bg: "grad", cyr: "град" },
      { en: "building", bg: "sgrada", cyr: "сграда" },
      { en: "street", bg: "ulitsa", cyr: "улица" },
      { en: "road", bg: "pat", cyr: "път" },
      { en: "bridge", bg: "most", cyr: "мост" },
      { en: "bank", bg: "banka", cyr: "банка" },
      { en: "post office", bg: "poshta", cyr: "поща" },
      { en: "restaurant", bg: "restorant", cyr: "ресторант" },
      { en: "theater", bg: "teatar", cyr: "театър" },
      { en: "cinema", bg: "kino", cyr: "кино" },
      { en: "factory", bg: "fabrika", cyr: "фабрика" },
      { en: "office", bg: "ofis", cyr: "офис" },
      { en: "corner", bg: "agal", cyr: "ъгъл" },
      { en: "center", bg: "tsentar", cyr: "център" },
      { en: "traffic", bg: "trafik", cyr: "трафик" },
      { en: "crossroads", bg: "krastovishte", cyr: "кръстовище" },
      { en: "sidewalk", bg: "trotoar", cyr: "тротоар" },
      { en: "fountain", bg: "cheshma", cyr: "чешма" },
      { en: "statue", bg: "statuya", cyr: "статуя" },
      { en: "tower", bg: "kula", cyr: "кула" },
      { en: "castle", bg: "zamak", cyr: "замък" },
      { en: "palace", bg: "dvorets", cyr: "дворец" },
      { en: "stadium", bg: "stadion", cyr: "стадион" },
      { en: "zoo", bg: "zoopark", cyr: "зоопарк" },
      { en: "parking", bg: "parking", cyr: "паркинг" },
      { en: "elevator", bg: "asansyor", cyr: "асансьор" },
      { en: "neighborhood", bg: "kvartal", cyr: "квартал" },
    ],
  },
  {
    id: "nature",
    name: "Nature & geography",
    emoji: "🏔️",
    hue: 150,
    words: [
      { en: "nature", bg: "priroda", cyr: "природа" },
      { en: "mountain", bg: "planina", cyr: "планина" },
      { en: "river", bg: "reka", cyr: "река" },
      { en: "sea", bg: "more", cyr: "море" },
      { en: "lake", bg: "ezero", cyr: "езеро" },
      { en: "ocean", bg: "okean", cyr: "океан" },
      { en: "island", bg: "ostrov", cyr: "остров" },
      { en: "forest", bg: "gora", cyr: "гора" },
      { en: "field", bg: "pole", cyr: "поле" },
      { en: "hill", bg: "halm", cyr: "хълм" },
      { en: "valley", bg: "dolina", cyr: "долина" },
      { en: "desert", bg: "pustinya", cyr: "пустиня" },
      { en: "cave", bg: "peshtera", cyr: "пещера" },
      { en: "waterfall", bg: "vodopad", cyr: "водопад" },
      { en: "coast", bg: "bryag", cyr: "бряг" },
      { en: "rock", bg: "skala", cyr: "скала" },
      { en: "stone", bg: "kamak", cyr: "камък" },
      { en: "sand", bg: "pyasak", cyr: "пясък" },
      { en: "soil", bg: "pochva", cyr: "почва" },
      { en: "world", bg: "svyat", cyr: "свят" },
      { en: "country", bg: "darzhava", cyr: "държава" },
      { en: "north", bg: "sever", cyr: "север" },
      { en: "south", bg: "yug", cyr: "юг" },
      { en: "east", bg: "iztok", cyr: "изток" },
      { en: "west", bg: "zapad", cyr: "запад" },
      { en: "border", bg: "granitsa", cyr: "граница" },
      { en: "map", bg: "karta", cyr: "карта" },
    ],
  },
  {
    id: "pronouns",
    name: "Pronouns & questions",
    emoji: "🙋",
    hue: 262,
    words: [
      { en: "I", bg: "az", cyr: "аз" },
      { en: "you", bg: "ti", cyr: "ти" },
      { en: "he", bg: "toy", cyr: "той" },
      { en: "she", bg: "tya", cyr: "тя" },
      { en: "it", bg: "to", cyr: "то" },
      { en: "we", bg: "nie", cyr: "ние" },
      { en: "you (plural)", bg: "vie", cyr: "вие" },
      { en: "they", bg: "te", cyr: "те" },
      { en: "me", bg: "men", cyr: "мен" },
      { en: "this", bg: "tova", cyr: "това" },
      { en: "that", bg: "onova", cyr: "онова" },
      { en: "these", bg: "tezi", cyr: "тези" },
      { en: "those", bg: "onezi", cyr: "онези" },
      { en: "here", bg: "tuk", cyr: "тук" },
      { en: "there", bg: "tam", cyr: "там" },
      { en: "who", bg: "koy", cyr: "кой" },
      { en: "what", bg: "kakvo", cyr: "какво" },
      { en: "whose", bg: "chiy", cyr: "чий" },
      { en: "everyone", bg: "vsichki", cyr: "всички" },
      { en: "someone", bg: "nyakoy", cyr: "някой" },
      { en: "no one", bg: "nikoy", cyr: "никой" },
      { en: "something", bg: "neshto", cyr: "нещо" },
      { en: "nothing", bg: "nishto", cyr: "нищо" },
      { en: "everything", bg: "vsichko", cyr: "всичко" },
      { en: "my", bg: "moy", cyr: "мой" },
      { en: "your", bg: "tvoy", cyr: "твой" },
      { en: "our", bg: "nash", cyr: "наш" },
      { en: "his", bg: "negov", cyr: "негов" },
    ],
  },
  {
    id: "prepositions",
    name: "Prepositions & directions",
    emoji: "🧭",
    hue: 188,
    words: [
      { en: "in", bg: "v", cyr: "в" },
      { en: "on", bg: "na", cyr: "на" },
      { en: "under", bg: "pod", cyr: "под" },
      { en: "above", bg: "nad", cyr: "над" },
      { en: "behind", bg: "zad", cyr: "зад" },
      { en: "in front of", bg: "pred", cyr: "пред" },
      { en: "next to", bg: "do", cyr: "до" },
      { en: "between", bg: "mezhdu", cyr: "между" },
      { en: "up", bg: "gore", cyr: "горе" },
      { en: "down", bg: "dolu", cyr: "долу" },
      { en: "inside", bg: "vatre", cyr: "вътре" },
      { en: "outside", bg: "navan", cyr: "навън" },
      { en: "with", bg: "s", cyr: "с" },
      { en: "without", bg: "bez", cyr: "без" },
      { en: "for", bg: "za", cyr: "за" },
      { en: "from", bg: "ot", cyr: "от" },
      { en: "to / toward", bg: "kam", cyr: "към" },
      { en: "about", bg: "otnosno", cyr: "относно" },
      { en: "after", bg: "sled", cyr: "след" },
      { en: "before", bg: "predi", cyr: "преди" },
      { en: "around", bg: "okolo", cyr: "около" },
      { en: "through", bg: "prez", cyr: "през" },
      { en: "against", bg: "sreshtu", cyr: "срещу" },
      { en: "left", bg: "lyavo", cyr: "ляво" },
      { en: "right", bg: "dyasno", cyr: "дясно" },
      { en: "near", bg: "blizo", cyr: "близо" },
      { en: "far", bg: "daleche", cyr: "далече" },
    ],
  },
  {
    id: "conjunctions",
    name: "Little words",
    emoji: "🔗",
    hue: 240,
    words: [
      { en: "and", bg: "i", cyr: "и" },
      { en: "or", bg: "ili", cyr: "или" },
      { en: "but", bg: "no", cyr: "но" },
      { en: "because", bg: "zashtoto", cyr: "защото" },
      { en: "if", bg: "ako", cyr: "ако" },
      { en: "so", bg: "taka", cyr: "така" },
      { en: "very", bg: "mnogo", cyr: "много" },
      { en: "only", bg: "samo", cyr: "само" },
      { en: "maybe", bg: "mozhe bi", cyr: "може би" },
      { en: "always", bg: "vinagi", cyr: "винаги" },
      { en: "never", bg: "nikoga", cyr: "никога" },
      { en: "often", bg: "chesto", cyr: "често" },
      { en: "sometimes", bg: "ponyakoga", cyr: "понякога" },
      { en: "then", bg: "togava", cyr: "тогава" },
      { en: "already", bg: "veche", cyr: "вече" },
      { en: "still / yet", bg: "oshte", cyr: "още" },
      { en: "again", bg: "otnovo", cyr: "отново" },
      { en: "also", bg: "sasho", cyr: "също" },
      { en: "well", bg: "dobre", cyr: "добре" },
      { en: "together", bg: "zaedno", cyr: "заедно" },
      { en: "almost", bg: "pochti", cyr: "почти" },
      { en: "enough", bg: "dostatachno", cyr: "достатъчно" },
      { en: "really", bg: "naistina", cyr: "наистина" },
      { en: "such", bg: "takav", cyr: "такъв" },
      { en: "both", bg: "dvete", cyr: "двете" },
      { en: "a little", bg: "malko", cyr: "малко" },
      { en: "more", bg: "poveche", cyr: "повече" },
    ],
  },
];

export function getTheme(id: string): Theme | undefined {
  return THEMES.find((t) => t.id === id);
}

// Normalize for comparison: lowercase, drop punctuation, collapse whitespace.
export function normalize(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}

// True if `input` matches `expected`. A "/" in expected marks alternatives,
// so "hand / arm" accepts either "hand" or "arm".
export function matches(input: string, expected: string): boolean {
  const got = normalize(input);
  if (!got) return false;
  const candidates = expected.split("/").map(normalize).filter(Boolean);
  candidates.push(normalize(expected));
  return candidates.includes(got);
}

// Weighted random index. `weights[i]` is the relative chance of picking i;
// a weight of 0 excludes that entry (used to avoid immediate repeats and to
// favour words the player keeps missing). `rng` is injectable for testing.
export function pickIndex(weights: number[], rng: () => number = Math.random): number {
  const total = weights.reduce((a, b) => a + (b > 0 ? b : 0), 0);
  if (total <= 0) return 0;
  let r = rng() * total;
  for (let i = 0; i < weights.length; i++) {
    if (weights[i] > 0) {
      r -= weights[i];
      if (r < 0) return i;
    }
  }
  // Fallback: last entry with a positive weight.
  for (let i = weights.length - 1; i >= 0; i--) if (weights[i] > 0) return i;
  return 0;
}
