// Bulgarian vocabulary, transliterated to Latin letters.
// `bg` is the accepted answer (Latin), `cyr` is the Cyrillic (shown + spoken).
// A "/" in a value marks alternative accepted answers (e.g. "hand / arm").

export type Word = {
  en: string;
  bg: string; // Bulgarian written in Latin letters
  cyr: string; // Cyrillic, shown as a learning aid and used for speech
};

export type Theme = {
  id: string;
  name: string;
  emoji: string;
  hue: number; // base hue used for the theme's accent gradient
  words: Word[];
};

export const THEMES: Theme[] = [
  {
    id: "everyday",
    name: "Everyday phrases",
    emoji: "💬",
    hue: 265,
    words: [
      { en: "hello", bg: "zdravey", cyr: "здравей" },
      { en: "hi", bg: "zdrasti", cyr: "здрасти" },
      { en: "goodbye", bg: "dovizhdane", cyr: "довиждане" },
      { en: "thank you", bg: "blagodarya", cyr: "благодаря" },
      { en: "please", bg: "molya", cyr: "моля" },
      { en: "yes", bg: "da", cyr: "да" },
      { en: "no", bg: "ne", cyr: "не" },
      { en: "good morning", bg: "dobro utro", cyr: "добро утро" },
      { en: "good afternoon", bg: "dobar den", cyr: "добър ден" },
      { en: "good evening", bg: "dobar vecher", cyr: "добър вечер" },
      { en: "good night", bg: "leka nosht", cyr: "лека нощ" },
      { en: "how are you", bg: "kak si", cyr: "как си" },
      { en: "I'm fine", bg: "dobre sam", cyr: "добре съм" },
      { en: "excuse me", bg: "izvinete", cyr: "извинете" },
      { en: "sorry", bg: "sazhalyavam", cyr: "съжалявам" },
      { en: "behind us", bg: "zad nas", cyr: "зад нас" },
      { en: "I love you", bg: "obicham te", cyr: "обичам те" },
      { en: "what's your name", bg: "kak se kazvash", cyr: "как се казваш" },
      { en: "my name is", bg: "kazvam se", cyr: "казвам се" },
      { en: "where", bg: "kade", cyr: "къде" },
      { en: "when", bg: "koga", cyr: "кога" },
      { en: "why", bg: "zashto", cyr: "защо" },
      { en: "who", bg: "koy", cyr: "кой" },
      { en: "how", bg: "kak", cyr: "как" },
      { en: "how much", bg: "kolko", cyr: "колко" },
      { en: "now", bg: "sega", cyr: "сега" },
      { en: "of course", bg: "razbira se", cyr: "разбира се" },
      { en: "I don't know", bg: "ne znam", cyr: "не знам" },
      { en: "I don't understand", bg: "ne razbiram", cyr: "не разбирам" },
      { en: "help", bg: "pomosht", cyr: "помощ" },
      { en: "cheers", bg: "nazdrave", cyr: "наздраве" },
    ],
  },
  {
    id: "food",
    name: "Food & drink",
    emoji: "🍽️",
    hue: 12,
    words: [
      { en: "water", bg: "voda", cyr: "вода" },
      { en: "bread", bg: "hlyab", cyr: "хляб" },
      { en: "coffee", bg: "kafe", cyr: "кафе" },
      { en: "beer", bg: "bira", cyr: "бира" },
      { en: "wine", bg: "vino", cyr: "вино" },
      { en: "milk", bg: "mlyako", cyr: "мляко" },
      { en: "cheese", bg: "sirene", cyr: "сирене" },
      { en: "yellow cheese", bg: "kashkaval", cyr: "кашкавал" },
      { en: "meat", bg: "meso", cyr: "месо" },
      { en: "chicken", bg: "pile", cyr: "пиле" },
      { en: "fish", bg: "riba", cyr: "риба" },
      { en: "egg", bg: "yaytse", cyr: "яйце" },
      { en: "apple", bg: "yabalka", cyr: "ябълка" },
      { en: "banana", bg: "banan", cyr: "банан" },
      { en: "tomato", bg: "domat", cyr: "домат" },
      { en: "cucumber", bg: "krastavitsa", cyr: "краставица" },
      { en: "potato", bg: "kartof", cyr: "картоф" },
      { en: "soup", bg: "supa", cyr: "супа" },
      { en: "salad", bg: "salata", cyr: "салата" },
      { en: "sugar", bg: "zahar", cyr: "захар" },
      { en: "salt", bg: "sol", cyr: "сол" },
      { en: "pepper", bg: "piper", cyr: "пипер" },
      { en: "tea", bg: "chay", cyr: "чай" },
      { en: "juice", bg: "sok", cyr: "сок" },
      { en: "yogurt", bg: "kiselo mlyako", cyr: "кисело мляко" },
      { en: "breakfast", bg: "zakuska", cyr: "закуска" },
      { en: "lunch", bg: "obyad", cyr: "обяд" },
      { en: "dinner", bg: "vecherya", cyr: "вечеря" },
      { en: "the bill", bg: "smetkata", cyr: "сметката" },
      { en: "delicious", bg: "vkusno", cyr: "вкусно" },
      { en: "spicy", bg: "lyuto", cyr: "люто" },
    ],
  },
  {
    id: "travel",
    name: "Travel & places",
    emoji: "✈️",
    hue: 192,
    words: [
      { en: "airport", bg: "letishte", cyr: "летище" },
      { en: "train", bg: "vlak", cyr: "влак" },
      { en: "bus", bg: "avtobus", cyr: "автобус" },
      { en: "car", bg: "kola", cyr: "кола" },
      { en: "taxi", bg: "taksi", cyr: "такси" },
      { en: "ticket", bg: "bilet", cyr: "билет" },
      { en: "hotel", bg: "hotel", cyr: "хотел" },
      { en: "room", bg: "staya", cyr: "стая" },
      { en: "street", bg: "ulitsa", cyr: "улица" },
      { en: "square", bg: "ploshtad", cyr: "площад" },
      { en: "city", bg: "grad", cyr: "град" },
      { en: "village", bg: "selo", cyr: "село" },
      { en: "left", bg: "lyavo", cyr: "ляво" },
      { en: "right", bg: "dyasno", cyr: "дясно" },
      { en: "straight ahead", bg: "napravo", cyr: "направо" },
      { en: "near", bg: "blizo", cyr: "близо" },
      { en: "far", bg: "daleche", cyr: "далече" },
      { en: "map", bg: "karta", cyr: "карта" },
      { en: "beach", bg: "plazh", cyr: "плаж" },
      { en: "sea", bg: "more", cyr: "море" },
      { en: "mountain", bg: "planina", cyr: "планина" },
      { en: "river", bg: "reka", cyr: "река" },
      { en: "forest", bg: "gora", cyr: "гора" },
      { en: "park", bg: "park", cyr: "парк" },
      { en: "church", bg: "tsarkva", cyr: "църква" },
      { en: "museum", bg: "muzey", cyr: "музей" },
      { en: "market", bg: "pazar", cyr: "пазар" },
      { en: "station", bg: "gara", cyr: "гара" },
      { en: "where is", bg: "kade e", cyr: "къде е" },
      { en: "passport", bg: "pasport", cyr: "паспорт" },
      { en: "luggage", bg: "bagazh", cyr: "багаж" },
    ],
  },
  {
    id: "numbers",
    name: "Numbers & time",
    emoji: "🔢",
    hue: 142,
    words: [
      { en: "zero", bg: "nula", cyr: "нула" },
      { en: "one", bg: "edno", cyr: "едно" },
      { en: "two", bg: "dve", cyr: "две" },
      { en: "three", bg: "tri", cyr: "три" },
      { en: "four", bg: "chetiri", cyr: "четири" },
      { en: "five", bg: "pet", cyr: "пет" },
      { en: "six", bg: "shest", cyr: "шест" },
      { en: "seven", bg: "sedem", cyr: "седем" },
      { en: "eight", bg: "osem", cyr: "осем" },
      { en: "nine", bg: "devet", cyr: "девет" },
      { en: "ten", bg: "deset", cyr: "десет" },
      { en: "eleven", bg: "edinadeset", cyr: "единадесет" },
      { en: "twelve", bg: "dvanadeset", cyr: "дванадесет" },
      { en: "twenty", bg: "dvadeset", cyr: "двадесет" },
      { en: "fifty", bg: "petdeset", cyr: "петдесет" },
      { en: "hundred", bg: "sto", cyr: "сто" },
      { en: "thousand", bg: "hilyada", cyr: "хиляда" },
      { en: "today", bg: "dnes", cyr: "днес" },
      { en: "tomorrow", bg: "utre", cyr: "утре" },
      { en: "yesterday", bg: "vchera", cyr: "вчера" },
      { en: "day", bg: "den", cyr: "ден" },
      { en: "week", bg: "sedmitsa", cyr: "седмица" },
      { en: "month", bg: "mesets", cyr: "месец" },
      { en: "year", bg: "godina", cyr: "година" },
      { en: "hour", bg: "chas", cyr: "час" },
      { en: "minute", bg: "minuta", cyr: "минута" },
      { en: "morning", bg: "sutrin", cyr: "сутрин" },
      { en: "evening", bg: "vecher", cyr: "вечер" },
      { en: "Monday", bg: "ponedelnik", cyr: "понеделник" },
      { en: "Friday", bg: "petak", cyr: "петък" },
      { en: "what time is it", bg: "kolko e chasat", cyr: "колко е часът" },
    ],
  },
  {
    id: "family",
    name: "Family & people",
    emoji: "👪",
    hue: 320,
    words: [
      { en: "mother", bg: "mayka", cyr: "майка" },
      { en: "father", bg: "bashta", cyr: "баща" },
      { en: "parents", bg: "roditeli", cyr: "родители" },
      { en: "son", bg: "sin", cyr: "син" },
      { en: "daughter", bg: "dashterya", cyr: "дъщеря" },
      { en: "child", bg: "dete", cyr: "дете" },
      { en: "children", bg: "detsa", cyr: "деца" },
      { en: "brother", bg: "brat", cyr: "брат" },
      { en: "sister", bg: "sestra", cyr: "сестра" },
      { en: "grandmother", bg: "baba", cyr: "баба" },
      { en: "grandfather", bg: "dyado", cyr: "дядо" },
      { en: "husband", bg: "saprug", cyr: "съпруг" },
      { en: "wife", bg: "sapruga", cyr: "съпруга" },
      { en: "friend", bg: "priyatel", cyr: "приятел" },
      { en: "girlfriend", bg: "priyatelka", cyr: "приятелка" },
      { en: "boy", bg: "momche", cyr: "момче" },
      { en: "girl", bg: "momiche", cyr: "момиче" },
      { en: "man", bg: "mazh", cyr: "мъж" },
      { en: "woman", bg: "zhena", cyr: "жена" },
      { en: "people", bg: "hora", cyr: "хора" },
      { en: "family", bg: "semeystvo", cyr: "семейство" },
      { en: "name", bg: "ime", cyr: "име" },
      { en: "neighbor", bg: "sased", cyr: "съсед" },
      { en: "guest", bg: "gost", cyr: "гост" },
    ],
  },
  {
    id: "body",
    name: "Body & health",
    emoji: "🩺",
    hue: 0,
    words: [
      { en: "head", bg: "glava", cyr: "глава" },
      { en: "hair", bg: "kosa", cyr: "коса" },
      { en: "eye", bg: "oko", cyr: "око" },
      { en: "eyes", bg: "ochi", cyr: "очи" },
      { en: "ear", bg: "uho", cyr: "ухо" },
      { en: "nose", bg: "nos", cyr: "нос" },
      { en: "mouth", bg: "usta", cyr: "уста" },
      { en: "tooth", bg: "zab", cyr: "зъб" },
      { en: "tongue", bg: "ezik", cyr: "език" },
      { en: "neck", bg: "vrat", cyr: "врат" },
      { en: "hand / arm", bg: "raka", cyr: "ръка" },
      { en: "finger", bg: "prast", cyr: "пръст" },
      { en: "leg / foot", bg: "krak", cyr: "крак" },
      { en: "heart", bg: "sartse", cyr: "сърце" },
      { en: "stomach", bg: "stomah", cyr: "стомах" },
      { en: "back", bg: "garb", cyr: "гръб" },
      { en: "blood", bg: "krav", cyr: "кръв" },
      { en: "skin", bg: "kozha", cyr: "кожа" },
      { en: "doctor", bg: "lekar", cyr: "лекар" },
      { en: "pharmacy", bg: "apteka", cyr: "аптека" },
      { en: "medicine", bg: "lekarstvo", cyr: "лекарство" },
      { en: "pain", bg: "bolka", cyr: "болка" },
      { en: "sick", bg: "bolen", cyr: "болен" },
      { en: "healthy", bg: "zdrav", cyr: "здрав" },
      { en: "hospital", bg: "bolnitsa", cyr: "болница" },
    ],
  },
  {
    id: "weather",
    name: "Weather & nature",
    emoji: "🌦️",
    hue: 205,
    words: [
      { en: "weather", bg: "vreme", cyr: "време" },
      { en: "sun", bg: "slantse", cyr: "слънце" },
      { en: "moon", bg: "luna", cyr: "луна" },
      { en: "star", bg: "zvezda", cyr: "звезда" },
      { en: "sky", bg: "nebe", cyr: "небе" },
      { en: "cloud", bg: "oblak", cyr: "облак" },
      { en: "rain", bg: "dazhd", cyr: "дъжд" },
      { en: "snow", bg: "snyag", cyr: "сняг" },
      { en: "wind", bg: "vyatar", cyr: "вятър" },
      { en: "storm", bg: "burya", cyr: "буря" },
      { en: "fog", bg: "magla", cyr: "мъгла" },
      { en: "hot", bg: "goreshto", cyr: "горещо" },
      { en: "cold", bg: "studeno", cyr: "студено" },
      { en: "warm", bg: "toplo", cyr: "топло" },
      { en: "ice", bg: "led", cyr: "лед" },
      { en: "fire", bg: "ogan", cyr: "огън" },
      { en: "earth", bg: "zemya", cyr: "земя" },
      { en: "tree", bg: "darvo", cyr: "дърво" },
      { en: "flower", bg: "tsvete", cyr: "цвете" },
      { en: "grass", bg: "treva", cyr: "трева" },
      { en: "animal", bg: "zhivotno", cyr: "животно" },
      { en: "spring", bg: "prolet", cyr: "пролет" },
      { en: "summer", bg: "lyato", cyr: "лято" },
      { en: "autumn", bg: "esen", cyr: "есен" },
      { en: "winter", bg: "zima", cyr: "зима" },
    ],
  },
  {
    id: "shopping",
    name: "Shopping & money",
    emoji: "🛍️",
    hue: 45,
    words: [
      { en: "shop", bg: "magazin", cyr: "магазин" },
      { en: "market", bg: "pazar", cyr: "пазар" },
      { en: "money", bg: "pari", cyr: "пари" },
      { en: "price", bg: "tsena", cyr: "цена" },
      { en: "cheap", bg: "evtino", cyr: "евтино" },
      { en: "expensive", bg: "skapo", cyr: "скъпо" },
      { en: "how much does it cost", bg: "kolko struva", cyr: "колко струва" },
      { en: "to buy", bg: "kupuvam", cyr: "купувам" },
      { en: "to pay", bg: "plashtam", cyr: "плащам" },
      { en: "to sell", bg: "prodavam", cyr: "продавам" },
      { en: "cash", bg: "v broy", cyr: "в брой" },
      { en: "receipt", bg: "kasova belezhka", cyr: "касова бележка" },
      { en: "bag", bg: "torba", cyr: "торба" },
      { en: "clothes", bg: "drehi", cyr: "дрехи" },
      { en: "shoes", bg: "obuvki", cyr: "обувки" },
      { en: "shirt", bg: "riza", cyr: "риза" },
      { en: "trousers", bg: "pantalon", cyr: "панталон" },
      { en: "dress", bg: "roklya", cyr: "рокля" },
      { en: "hat", bg: "shapka", cyr: "шапка" },
      { en: "size", bg: "razmer", cyr: "размер" },
      { en: "open", bg: "otvoreno", cyr: "отворено" },
      { en: "closed", bg: "zatvoreno", cyr: "затворено" },
      { en: "sale", bg: "namalenie", cyr: "намаление" },
      { en: "gift", bg: "podarak", cyr: "подарък" },
    ],
  },
  {
    id: "verbs",
    name: "Common verbs",
    emoji: "🏃",
    hue: 160,
    words: [
      { en: "to be", bg: "sam", cyr: "съм" },
      { en: "to have", bg: "imam", cyr: "имам" },
      { en: "to want", bg: "iskam", cyr: "искам" },
      { en: "to be able", bg: "moga", cyr: "мога" },
      { en: "to go", bg: "otivam", cyr: "отивам" },
      { en: "to come", bg: "idvam", cyr: "идвам" },
      { en: "to eat", bg: "yam", cyr: "ям" },
      { en: "to drink", bg: "piya", cyr: "пия" },
      { en: "to sleep", bg: "spya", cyr: "спя" },
      { en: "to speak", bg: "govorya", cyr: "говоря" },
      { en: "to know", bg: "znam", cyr: "знам" },
      { en: "to see", bg: "vizhdam", cyr: "виждам" },
      { en: "to make / do", bg: "pravya", cyr: "правя" },
      { en: "to give", bg: "davam", cyr: "давам" },
      { en: "to take", bg: "vzemam", cyr: "взимам" },
      { en: "to read", bg: "cheta", cyr: "чета" },
      { en: "to write", bg: "pisha", cyr: "пиша" },
      { en: "to work", bg: "rabotya", cyr: "работя" },
      { en: "to live", bg: "zhiveya", cyr: "живея" },
      { en: "to love", bg: "obicham", cyr: "обичам" },
      { en: "to think", bg: "mislya", cyr: "мисля" },
      { en: "to open", bg: "otvaryam", cyr: "отварям" },
      { en: "to wait", bg: "chakam", cyr: "чакам" },
      { en: "to walk", bg: "varvya", cyr: "вървя" },
      { en: "to run", bg: "byagam", cyr: "бягам" },
      { en: "to help", bg: "pomagam", cyr: "помагам" },
    ],
  },
  {
    id: "colors",
    name: "Colors & shapes",
    emoji: "🎨",
    hue: 285,
    words: [
      { en: "color", bg: "tsvyat", cyr: "цвят" },
      { en: "red", bg: "cherveno", cyr: "червено" },
      { en: "blue", bg: "sinyo", cyr: "синьо" },
      { en: "green", bg: "zeleno", cyr: "зелено" },
      { en: "yellow", bg: "zhalto", cyr: "жълто" },
      { en: "white", bg: "byalo", cyr: "бяло" },
      { en: "black", bg: "cherno", cyr: "черно" },
      { en: "orange", bg: "oranzhevo", cyr: "оранжево" },
      { en: "purple", bg: "lilavo", cyr: "лилаво" },
      { en: "pink", bg: "rozovo", cyr: "розово" },
      { en: "brown", bg: "kafyavo", cyr: "кафяво" },
      { en: "grey", bg: "sivo", cyr: "сиво" },
      { en: "gold", bg: "zlatno", cyr: "златно" },
      { en: "silver", bg: "srebarno", cyr: "сребърно" },
      { en: "light", bg: "svetlo", cyr: "светло" },
      { en: "dark", bg: "tamno", cyr: "тъмно" },
      { en: "circle", bg: "krag", cyr: "кръг" },
      { en: "square", bg: "kvadrat", cyr: "квадрат" },
      { en: "triangle", bg: "triagalnik", cyr: "триъгълник" },
      { en: "line", bg: "liniya", cyr: "линия" },
      { en: "dot", bg: "tochka", cyr: "точка" },
      { en: "round", bg: "kragal", cyr: "кръгъл" },
      { en: "big", bg: "golyam", cyr: "голям" },
      { en: "small", bg: "malak", cyr: "малък" },
      { en: "bright", bg: "yarak", cyr: "ярък" },
      { en: "shape", bg: "forma", cyr: "форма" },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    emoji: "🐾",
    hue: 35,
    words: [
      { en: "animal", bg: "zhivotno", cyr: "животно" },
      { en: "dog", bg: "kuche", cyr: "куче" },
      { en: "cat", bg: "kotka", cyr: "котка" },
      { en: "horse", bg: "kon", cyr: "кон" },
      { en: "cow", bg: "krava", cyr: "крава" },
      { en: "pig", bg: "svinya", cyr: "свиня" },
      { en: "sheep", bg: "ovtsa", cyr: "овца" },
      { en: "goat", bg: "koza", cyr: "коза" },
      { en: "hen", bg: "kokoshka", cyr: "кокошка" },
      { en: "rooster", bg: "petel", cyr: "петел" },
      { en: "duck", bg: "patitsa", cyr: "патица" },
      { en: "bird", bg: "ptitsa", cyr: "птица" },
      { en: "rabbit", bg: "zaek", cyr: "заек" },
      { en: "mouse", bg: "mishka", cyr: "мишка" },
      { en: "bear", bg: "mechka", cyr: "мечка" },
      { en: "wolf", bg: "valk", cyr: "вълк" },
      { en: "fox", bg: "lisitsa", cyr: "лисица" },
      { en: "lion", bg: "lav", cyr: "лъв" },
      { en: "elephant", bg: "slon", cyr: "слон" },
      { en: "monkey", bg: "maymuna", cyr: "маймуна" },
      { en: "snake", bg: "zmiya", cyr: "змия" },
      { en: "frog", bg: "zhaba", cyr: "жаба" },
      { en: "bee", bg: "pchela", cyr: "пчела" },
      { en: "spider", bg: "payak", cyr: "паяк" },
      { en: "butterfly", bg: "peperuda", cyr: "пеперуда" },
      { en: "turtle", bg: "kostenurka", cyr: "костенурка" },
      { en: "deer", bg: "elen", cyr: "елен" },
    ],
  },
  {
    id: "home",
    name: "House & home",
    emoji: "🏠",
    hue: 172,
    words: [
      { en: "house", bg: "kashta", cyr: "къща" },
      { en: "home", bg: "dom", cyr: "дом" },
      { en: "door", bg: "vrata", cyr: "врата" },
      { en: "window", bg: "prozorets", cyr: "прозорец" },
      { en: "wall", bg: "stena", cyr: "стена" },
      { en: "floor", bg: "pod", cyr: "под" },
      { en: "ceiling", bg: "tavan", cyr: "таван" },
      { en: "roof", bg: "pokriv", cyr: "покрив" },
      { en: "room", bg: "staya", cyr: "стая" },
      { en: "kitchen", bg: "kuhnya", cyr: "кухня" },
      { en: "bedroom", bg: "spalnya", cyr: "спалня" },
      { en: "bathroom", bg: "banya", cyr: "баня" },
      { en: "table", bg: "masa", cyr: "маса" },
      { en: "chair", bg: "stol", cyr: "стол" },
      { en: "bed", bg: "leglo", cyr: "легло" },
      { en: "sofa", bg: "divan", cyr: "диван" },
      { en: "key", bg: "klyuch", cyr: "ключ" },
      { en: "lamp", bg: "lampa", cyr: "лампа" },
      { en: "mirror", bg: "ogledalo", cyr: "огледало" },
      { en: "shelf", bg: "raft", cyr: "рафт" },
      { en: "cupboard", bg: "shkaf", cyr: "шкаф" },
      { en: "carpet", bg: "kilim", cyr: "килим" },
      { en: "stairs", bg: "stalbi", cyr: "стълби" },
      { en: "garden", bg: "gradina", cyr: "градина" },
      { en: "yard", bg: "dvor", cyr: "двор" },
      { en: "garage", bg: "garazh", cyr: "гараж" },
      { en: "television", bg: "televizor", cyr: "телевизор" },
      { en: "fridge", bg: "hladilnik", cyr: "хладилник" },
    ],
  },
  {
    id: "jobs",
    name: "Jobs & professions",
    emoji: "💼",
    hue: 222,
    words: [
      { en: "work / job", bg: "rabota", cyr: "работа" },
      { en: "teacher", bg: "uchitel", cyr: "учител" },
      { en: "student", bg: "student", cyr: "студент" },
      { en: "doctor", bg: "lekar", cyr: "лекар" },
      { en: "nurse", bg: "meditsinska sestra", cyr: "медицинска сестра" },
      { en: "engineer", bg: "inzhener", cyr: "инженер" },
      { en: "lawyer", bg: "advokat", cyr: "адвокат" },
      { en: "police officer", bg: "politsay", cyr: "полицай" },
      { en: "firefighter", bg: "pozharnikar", cyr: "пожарникар" },
      { en: "cook / chef", bg: "gotvach", cyr: "готвач" },
      { en: "waiter", bg: "servityor", cyr: "сервитьор" },
      { en: "driver", bg: "shofyor", cyr: "шофьор" },
      { en: "farmer", bg: "fermer", cyr: "фермер" },
      { en: "builder", bg: "stroitel", cyr: "строител" },
      { en: "writer", bg: "pisatel", cyr: "писател" },
      { en: "artist", bg: "hudozhnik", cyr: "художник" },
      { en: "musician", bg: "muzikant", cyr: "музикант" },
      { en: "actor", bg: "aktyor", cyr: "актьор" },
      { en: "singer", bg: "pevets", cyr: "певец" },
      { en: "scientist", bg: "uchen", cyr: "учен" },
      { en: "programmer", bg: "programist", cyr: "програмист" },
      { en: "salesperson", bg: "prodavach", cyr: "продавач" },
      { en: "manager", bg: "menidzhar", cyr: "мениджър" },
      { en: "boss", bg: "shef", cyr: "шеф" },
      { en: "worker", bg: "rabotnik", cyr: "работник" },
      { en: "pilot", bg: "pilot", cyr: "пилот" },
      { en: "soldier", bg: "voynik", cyr: "войник" },
    ],
  },
  {
    id: "tech",
    name: "Technology & phone",
    emoji: "📱",
    hue: 200,
    words: [
      { en: "phone", bg: "telefon", cyr: "телефон" },
      { en: "computer", bg: "kompyutar", cyr: "компютър" },
      { en: "laptop", bg: "laptop", cyr: "лаптоп" },
      { en: "screen", bg: "ekran", cyr: "екран" },
      { en: "keyboard", bg: "klaviatura", cyr: "клавиатура" },
      { en: "mouse", bg: "mishka", cyr: "мишка" },
      { en: "internet", bg: "internet", cyr: "интернет" },
      { en: "email", bg: "imeyl", cyr: "имейл" },
      { en: "message", bg: "saobshtenie", cyr: "съобщение" },
      { en: "password", bg: "parola", cyr: "парола" },
      { en: "file", bg: "fayl", cyr: "файл" },
      { en: "app", bg: "prilozhenie", cyr: "приложение" },
      { en: "battery", bg: "bateriya", cyr: "батерия" },
      { en: "charger", bg: "zaryadno", cyr: "зарядно" },
      { en: "camera", bg: "kamera", cyr: "камера" },
      { en: "photo", bg: "snimka", cyr: "снимка" },
      { en: "video", bg: "video", cyr: "видео" },
      { en: "button", bg: "kopche", cyr: "копче" },
      { en: "network", bg: "mrezha", cyr: "мрежа" },
      { en: "signal", bg: "signal", cyr: "сигнал" },
      { en: "to call", bg: "obazhdam se", cyr: "обаждам се" },
      { en: "to download", bg: "svalyam", cyr: "свалям" },
      { en: "to click", bg: "klikam", cyr: "кликам" },
      { en: "smartphone", bg: "smartfon", cyr: "смартфон" },
      { en: "to charge", bg: "zarezhdam", cyr: "зареждам" },
      { en: "headphones", bg: "slushalki", cyr: "слушалки" },
    ],
  },
  {
    id: "emotions",
    name: "Emotions & feelings",
    emoji: "😊",
    hue: 350,
    words: [
      { en: "happy", bg: "shtastliv", cyr: "щастлив" },
      { en: "sad", bg: "tazhen", cyr: "тъжен" },
      { en: "angry", bg: "yadosan", cyr: "ядосан" },
      { en: "afraid", bg: "uplashen", cyr: "уплашен" },
      { en: "tired", bg: "umoren", cyr: "уморен" },
      { en: "bored", bg: "otegchen", cyr: "отегчен" },
      { en: "surprised", bg: "iznenadan", cyr: "изненадан" },
      { en: "excited", bg: "razvalnuvan", cyr: "развълнуван" },
      { en: "calm", bg: "spokoen", cyr: "спокоен" },
      { en: "nervous", bg: "nervozen", cyr: "нервозен" },
      { en: "proud", bg: "gord", cyr: "горд" },
      { en: "shy", bg: "sramezhliv", cyr: "срамежлив" },
      { en: "jealous", bg: "revniv", cyr: "ревнив" },
      { en: "lonely", bg: "samoten", cyr: "самотен" },
      { en: "confused", bg: "obarkan", cyr: "объркан" },
      { en: "love", bg: "lyubov", cyr: "любов" },
      { en: "fear", bg: "strah", cyr: "страх" },
      { en: "joy", bg: "radost", cyr: "радост" },
      { en: "anger", bg: "gnyav", cyr: "гняв" },
      { en: "hope", bg: "nadezhda", cyr: "надежда" },
      { en: "feeling", bg: "chuvstvo", cyr: "чувство" },
      { en: "to feel", bg: "chuvstvam", cyr: "чувствам" },
      { en: "to laugh", bg: "smeya se", cyr: "смея се" },
      { en: "to cry", bg: "placha", cyr: "плача" },
      { en: "to smile", bg: "usmihvam se", cyr: "усмихвам се" },
      { en: "glad", bg: "dovolen", cyr: "доволен" },
      { en: "hungry", bg: "gladen", cyr: "гладен" },
      { en: "thirsty", bg: "zhaden", cyr: "жаден" },
    ],
  },
  {
    id: "adjectives",
    name: "Adjectives",
    emoji: "✨",
    hue: 95,
    words: [
      { en: "good", bg: "dobar", cyr: "добър" },
      { en: "bad", bg: "losh", cyr: "лош" },
      { en: "new", bg: "nov", cyr: "нов" },
      { en: "old", bg: "star", cyr: "стар" },
      { en: "young", bg: "mlad", cyr: "млад" },
      { en: "hot", bg: "goresht", cyr: "горещ" },
      { en: "cold", bg: "studen", cyr: "студен" },
      { en: "fast", bg: "barz", cyr: "бърз" },
      { en: "slow", bg: "baven", cyr: "бавен" },
      { en: "easy", bg: "lesen", cyr: "лесен" },
      { en: "hard / difficult", bg: "truden", cyr: "труден" },
      { en: "beautiful", bg: "krasiv", cyr: "красив" },
      { en: "ugly", bg: "grozen", cyr: "грозен" },
      { en: "strong", bg: "silen", cyr: "силен" },
      { en: "weak", bg: "slab", cyr: "слаб" },
      { en: "rich", bg: "bogat", cyr: "богат" },
      { en: "poor", bg: "beden", cyr: "беден" },
      { en: "clean", bg: "chist", cyr: "чист" },
      { en: "dirty", bg: "mrasen", cyr: "мръсен" },
      { en: "full", bg: "palen", cyr: "пълен" },
      { en: "empty", bg: "prazen", cyr: "празен" },
      { en: "long", bg: "dalag", cyr: "дълъг" },
      { en: "short", bg: "kas", cyr: "къс" },
      { en: "tall / high", bg: "visok", cyr: "висок" },
      { en: "low", bg: "nisak", cyr: "нисък" },
      { en: "expensive", bg: "skap", cyr: "скъп" },
      { en: "important", bg: "vazhen", cyr: "важен" },
      { en: "wide", bg: "shirok", cyr: "широк" },
    ],
  },
  {
    id: "sports",
    name: "Sports & hobbies",
    emoji: "⚽",
    hue: 128,
    words: [
      { en: "sport", bg: "sport", cyr: "спорт" },
      { en: "game", bg: "igra", cyr: "игра" },
      { en: "ball", bg: "topka", cyr: "топка" },
      { en: "football", bg: "futbol", cyr: "футбол" },
      { en: "basketball", bg: "basketbol", cyr: "баскетбол" },
      { en: "tennis", bg: "tenis", cyr: "тенис" },
      { en: "to play", bg: "igraya", cyr: "играя" },
      { en: "to swim", bg: "pluvam", cyr: "плувам" },
      { en: "to jump", bg: "skacham", cyr: "скачам" },
      { en: "to dance", bg: "tantsuvam", cyr: "танцувам" },
      { en: "to sing", bg: "peya", cyr: "пея" },
      { en: "music", bg: "muzika", cyr: "музика" },
      { en: "film / movie", bg: "film", cyr: "филм" },
      { en: "hobby", bg: "hobi", cyr: "хоби" },
      { en: "to draw", bg: "risuvam", cyr: "рисувам" },
      { en: "team", bg: "otbor", cyr: "отбор" },
      { en: "player", bg: "igrach", cyr: "играч" },
      { en: "winner", bg: "pobeditel", cyr: "победител" },
      { en: "to win", bg: "pechelya", cyr: "печеля" },
      { en: "to lose", bg: "gubya", cyr: "губя" },
      { en: "gym", bg: "fitnes", cyr: "фитнес" },
      { en: "bicycle", bg: "kolelo", cyr: "колело" },
      { en: "to ride a bike", bg: "karam kolelo", cyr: "карам колело" },
      { en: "chess", bg: "shah", cyr: "шах" },
      { en: "guitar", bg: "kitara", cyr: "китара" },
      { en: "ski", bg: "ski", cyr: "ски" },
    ],
  },
  {
    id: "school",
    name: "School & education",
    emoji: "🎓",
    hue: 52,
    words: [
      { en: "school", bg: "uchilishte", cyr: "училище" },
      { en: "university", bg: "universitet", cyr: "университет" },
      { en: "lesson", bg: "urok", cyr: "урок" },
      { en: "pupil", bg: "uchenik", cyr: "ученик" },
      { en: "notebook", bg: "tetradka", cyr: "тетрадка" },
      { en: "pen", bg: "himikalka", cyr: "химикалка" },
      { en: "pencil", bg: "moliv", cyr: "молив" },
      { en: "paper", bg: "hartiya", cyr: "хартия" },
      { en: "desk", bg: "chin", cyr: "чин" },
      { en: "board", bg: "daska", cyr: "дъска" },
      { en: "homework", bg: "domashno", cyr: "домашно" },
      { en: "exam", bg: "izpit", cyr: "изпит" },
      { en: "test", bg: "test", cyr: "тест" },
      { en: "grade / mark", bg: "otsenka", cyr: "оценка" },
      { en: "question", bg: "vapros", cyr: "въпрос" },
      { en: "answer", bg: "otgovor", cyr: "отговор" },
      { en: "word", bg: "duma", cyr: "дума" },
      { en: "letter", bg: "bukva", cyr: "буква" },
      { en: "number", bg: "chislo", cyr: "число" },
      { en: "to learn", bg: "ucha", cyr: "уча" },
      { en: "to teach", bg: "prepodavam", cyr: "преподавам" },
      { en: "knowledge", bg: "znanie", cyr: "знание" },
      { en: "library", bg: "biblioteka", cyr: "библиотека" },
      { en: "dictionary", bg: "rechnik", cyr: "речник" },
      { en: "alphabet", bg: "azbuka", cyr: "азбука" },
      { en: "language", bg: "ezik", cyr: "език" },
      { en: "book", bg: "kniga", cyr: "книга" },
    ],
  },
  {
    id: "kitchen",
    name: "Kitchen & cooking",
    emoji: "🍳",
    hue: 18,
    words: [
      { en: "kitchen", bg: "kuhnya", cyr: "кухня" },
      { en: "plate", bg: "chiniya", cyr: "чиния" },
      { en: "bowl", bg: "kupa", cyr: "купа" },
      { en: "cup", bg: "chasha", cyr: "чаша" },
      { en: "spoon", bg: "lazhitsa", cyr: "лъжица" },
      { en: "fork", bg: "vilitsa", cyr: "вилица" },
      { en: "knife", bg: "nozh", cyr: "нож" },
      { en: "pot", bg: "tendzhera", cyr: "тенджера" },
      { en: "pan", bg: "tigan", cyr: "тиган" },
      { en: "oven", bg: "furna", cyr: "фурна" },
      { en: "stove", bg: "pechka", cyr: "печка" },
      { en: "to cook", bg: "gotvya", cyr: "готвя" },
      { en: "to bake", bg: "peka", cyr: "пека" },
      { en: "to fry", bg: "parzha", cyr: "пържа" },
      { en: "to boil", bg: "varya", cyr: "варя" },
      { en: "to cut", bg: "rezha", cyr: "режа" },
      { en: "to add", bg: "dobavyam", cyr: "добавям" },
      { en: "recipe", bg: "retsepta", cyr: "рецепта" },
      { en: "ingredient", bg: "sastavka", cyr: "съставка" },
      { en: "flour", bg: "brashno", cyr: "брашно" },
      { en: "oil", bg: "olio", cyr: "олио" },
      { en: "butter", bg: "maslo", cyr: "масло" },
      { en: "rice", bg: "oriz", cyr: "ориз" },
      { en: "pasta", bg: "makaroni", cyr: "макарони" },
      { en: "to taste", bg: "opitvam", cyr: "опитвам" },
      { en: "napkin", bg: "salfetka", cyr: "салфетка" },
      { en: "towel", bg: "karpa", cyr: "кърпа" },
    ],
  },
  {
    id: "city",
    name: "City & buildings",
    emoji: "🏙️",
    hue: 210,
    words: [
      { en: "city", bg: "grad", cyr: "град" },
      { en: "building", bg: "sgrada", cyr: "сграда" },
      { en: "street", bg: "ulitsa", cyr: "улица" },
      { en: "road", bg: "pat", cyr: "път" },
      { en: "bridge", bg: "most", cyr: "мост" },
      { en: "bank", bg: "banka", cyr: "банка" },
      { en: "post office", bg: "poshta", cyr: "поща" },
      { en: "restaurant", bg: "restorant", cyr: "ресторант" },
      { en: "theater", bg: "teatar", cyr: "театър" },
      { en: "cinema", bg: "kino", cyr: "кино" },
      { en: "factory", bg: "fabrika", cyr: "фабрика" },
      { en: "office", bg: "ofis", cyr: "офис" },
      { en: "corner", bg: "agal", cyr: "ъгъл" },
      { en: "center", bg: "tsentar", cyr: "център" },
      { en: "traffic", bg: "trafik", cyr: "трафик" },
      { en: "crossroads", bg: "krastovishte", cyr: "кръстовище" },
      { en: "sidewalk", bg: "trotoar", cyr: "тротоар" },
      { en: "fountain", bg: "cheshma", cyr: "чешма" },
      { en: "statue", bg: "statuya", cyr: "статуя" },
      { en: "tower", bg: "kula", cyr: "кула" },
      { en: "castle", bg: "zamak", cyr: "замък" },
      { en: "palace", bg: "dvorets", cyr: "дворец" },
      { en: "stadium", bg: "stadion", cyr: "стадион" },
      { en: "zoo", bg: "zoopark", cyr: "зоопарк" },
      { en: "parking", bg: "parking", cyr: "паркинг" },
      { en: "elevator", bg: "asansyor", cyr: "асансьор" },
      { en: "neighborhood", bg: "kvartal", cyr: "квартал" },
    ],
  },
  {
    id: "nature",
    name: "Nature & geography",
    emoji: "🏔️",
    hue: 150,
    words: [
      { en: "nature", bg: "priroda", cyr: "природа" },
      { en: "mountain", bg: "planina", cyr: "планина" },
      { en: "river", bg: "reka", cyr: "река" },
      { en: "sea", bg: "more", cyr: "море" },
      { en: "lake", bg: "ezero", cyr: "езеро" },
      { en: "ocean", bg: "okean", cyr: "океан" },
      { en: "island", bg: "ostrov", cyr: "остров" },
      { en: "forest", bg: "gora", cyr: "гора" },
      { en: "field", bg: "pole", cyr: "поле" },
      { en: "hill", bg: "halm", cyr: "хълм" },
      { en: "valley", bg: "dolina", cyr: "долина" },
      { en: "desert", bg: "pustinya", cyr: "пустиня" },
      { en: "cave", bg: "peshtera", cyr: "пещера" },
      { en: "waterfall", bg: "vodopad", cyr: "водопад" },
      { en: "coast", bg: "bryag", cyr: "бряг" },
      { en: "rock", bg: "skala", cyr: "скала" },
      { en: "stone", bg: "kamak", cyr: "камък" },
      { en: "sand", bg: "pyasak", cyr: "пясък" },
      { en: "soil", bg: "pochva", cyr: "почва" },
      { en: "world", bg: "svyat", cyr: "свят" },
      { en: "country", bg: "darzhava", cyr: "държава" },
      { en: "north", bg: "sever", cyr: "север" },
      { en: "south", bg: "yug", cyr: "юг" },
      { en: "east", bg: "iztok", cyr: "изток" },
      { en: "west", bg: "zapad", cyr: "запад" },
      { en: "border", bg: "granitsa", cyr: "граница" },
      { en: "map", bg: "karta", cyr: "карта" },
    ],
  },
  {
    id: "pronouns",
    name: "Pronouns & questions",
    emoji: "🙋",
    hue: 262,
    words: [
      { en: "I", bg: "az", cyr: "аз" },
      { en: "you", bg: "ti", cyr: "ти" },
      { en: "he", bg: "toy", cyr: "той" },
      { en: "she", bg: "tya", cyr: "тя" },
      { en: "it", bg: "to", cyr: "то" },
      { en: "we", bg: "nie", cyr: "ние" },
      { en: "you (plural)", bg: "vie", cyr: "вие" },
      { en: "they", bg: "te", cyr: "те" },
      { en: "me", bg: "men", cyr: "мен" },
      { en: "this", bg: "tova", cyr: "това" },
      { en: "that", bg: "onova", cyr: "онова" },
      { en: "these", bg: "tezi", cyr: "тези" },
      { en: "those", bg: "onezi", cyr: "онези" },
      { en: "here", bg: "tuk", cyr: "тук" },
      { en: "there", bg: "tam", cyr: "там" },
      { en: "who", bg: "koy", cyr: "кой" },
      { en: "what", bg: "kakvo", cyr: "какво" },
      { en: "whose", bg: "chiy", cyr: "чий" },
      { en: "everyone", bg: "vsichki", cyr: "всички" },
      { en: "someone", bg: "nyakoy", cyr: "някой" },
      { en: "no one", bg: "nikoy", cyr: "никой" },
      { en: "something", bg: "neshto", cyr: "нещо" },
      { en: "nothing", bg: "nishto", cyr: "нищо" },
      { en: "everything", bg: "vsichko", cyr: "всичко" },
      { en: "my", bg: "moy", cyr: "мой" },
      { en: "your", bg: "tvoy", cyr: "твой" },
      { en: "our", bg: "nash", cyr: "наш" },
      { en: "his", bg: "negov", cyr: "негов" },
    ],
  },
  {
    id: "prepositions",
    name: "Prepositions & directions",
    emoji: "🧭",
    hue: 188,
    words: [
      { en: "in", bg: "v", cyr: "в" },
      { en: "on", bg: "na", cyr: "на" },
      { en: "under", bg: "pod", cyr: "под" },
      { en: "above", bg: "nad", cyr: "над" },
      { en: "behind", bg: "zad", cyr: "зад" },
      { en: "in front of", bg: "pred", cyr: "пред" },
      { en: "next to", bg: "do", cyr: "до" },
      { en: "between", bg: "mezhdu", cyr: "между" },
      { en: "up", bg: "gore", cyr: "горе" },
      { en: "down", bg: "dolu", cyr: "долу" },
      { en: "inside", bg: "vatre", cyr: "вътре" },
      { en: "outside", bg: "navan", cyr: "навън" },
      { en: "with", bg: "s", cyr: "с" },
      { en: "without", bg: "bez", cyr: "без" },
      { en: "for", bg: "za", cyr: "за" },
      { en: "from", bg: "ot", cyr: "от" },
      { en: "to / toward", bg: "kam", cyr: "към" },
      { en: "about", bg: "otnosno", cyr: "относно" },
      { en: "after", bg: "sled", cyr: "след" },
      { en: "before", bg: "predi", cyr: "преди" },
      { en: "around", bg: "okolo", cyr: "около" },
      { en: "through", bg: "prez", cyr: "през" },
      { en: "against", bg: "sreshtu", cyr: "срещу" },
      { en: "left", bg: "lyavo", cyr: "ляво" },
      { en: "right", bg: "dyasno", cyr: "дясно" },
      { en: "near", bg: "blizo", cyr: "близо" },
      { en: "far", bg: "daleche", cyr: "далече" },
    ],
  },
  {
    id: "conjunctions",
    name: "Little words",
    emoji: "🔗",
    hue: 240,
    words: [
      { en: "and", bg: "i", cyr: "и" },
      { en: "or", bg: "ili", cyr: "или" },
      { en: "but", bg: "no", cyr: "но" },
      { en: "because", bg: "zashtoto", cyr: "защото" },
      { en: "if", bg: "ako", cyr: "ако" },
      { en: "so", bg: "taka", cyr: "така" },
      { en: "very", bg: "mnogo", cyr: "много" },
      { en: "only", bg: "samo", cyr: "само" },
      { en: "maybe", bg: "mozhe bi", cyr: "може би" },
      { en: "always", bg: "vinagi", cyr: "винаги" },
      { en: "never", bg: "nikoga", cyr: "никога" },
      { en: "often", bg: "chesto", cyr: "често" },
      { en: "sometimes", bg: "ponyakoga", cyr: "понякога" },
      { en: "then", bg: "togava", cyr: "тогава" },
      { en: "already", bg: "veche", cyr: "вече" },
      { en: "still / yet", bg: "oshte", cyr: "още" },
      { en: "again", bg: "otnovo", cyr: "отново" },
      { en: "also", bg: "sasho", cyr: "също" },
      { en: "well", bg: "dobre", cyr: "добре" },
      { en: "together", bg: "zaedno", cyr: "заедно" },
      { en: "almost", bg: "pochti", cyr: "почти" },
      { en: "enough", bg: "dostatachno", cyr: "достатъчно" },
      { en: "really", bg: "naistina", cyr: "наистина" },
      { en: "such", bg: "takav", cyr: "такъв" },
      { en: "both", bg: "dvete", cyr: "двете" },
      { en: "a little", bg: "malko", cyr: "малко" },
      { en: "more", bg: "poveche", cyr: "повече" },
    ],
  },
  {
    id: "restaurant",
    name: "Restaurant & dining",
    emoji: "🍴",
    hue: 28,
    words: [
      { en: "restaurant", bg: "restorant", cyr: "ресторант" },
      { en: "menu", bg: "menyu", cyr: "меню" },
      { en: "order", bg: "porachka", cyr: "поръчка" },
      { en: "to order", bg: "porachvam", cyr: "поръчвам" },
      { en: "bill", bg: "smetka", cyr: "сметка" },
      { en: "tip", bg: "baksish", cyr: "бакшиш" },
      { en: "glass", bg: "chasha", cyr: "чаша" },
      { en: "dessert", bg: "desert", cyr: "десерт" },
      { en: "starter", bg: "predyastie", cyr: "предястие" },
      { en: "main course", bg: "osnovno yastie", cyr: "основно ястие" },
      { en: "drink", bg: "napitka", cyr: "напитка" },
      { en: "dish", bg: "yastie", cyr: "ястие" },
      { en: "bottle", bg: "butilka", cyr: "бутилка" },
      { en: "to reserve", bg: "rezerviram", cyr: "резервирам" },
      { en: "reservation", bg: "rezervatsiya", cyr: "резервация" },
      { en: "sweet", bg: "sladko", cyr: "сладко" },
      { en: "sour", bg: "kiselo", cyr: "кисело" },
      { en: "fresh", bg: "presen", cyr: "пресен" },
      { en: "waiter", bg: "servityor", cyr: "сервитьор" },
      { en: "waitress", bg: "servityorka", cyr: "сервитьорка" },
      { en: "table", bg: "masa", cyr: "маса" },
      { en: "fork", bg: "vilitsa", cyr: "вилица" },
      { en: "knife", bg: "nozh", cyr: "нож" },
      { en: "plate", bg: "chiniya", cyr: "чиния" },
      { en: "napkin", bg: "salfetka", cyr: "салфетка" },
      { en: "spoon", bg: "lazhitsa", cyr: "лъжица" },
      { en: "to serve", bg: "serviram", cyr: "сервирам" },
    ],
  },
  {
    id: "transport",
    name: "Transport & vehicles",
    emoji: "🚗",
    hue: 196,
    words: [
      { en: "car", bg: "kola", cyr: "кола" },
      { en: "bus", bg: "avtobus", cyr: "автобус" },
      { en: "train", bg: "vlak", cyr: "влак" },
      { en: "plane", bg: "samolet", cyr: "самолет" },
      { en: "ship", bg: "korab", cyr: "кораб" },
      { en: "boat", bg: "lodka", cyr: "лодка" },
      { en: "bicycle", bg: "kolelo", cyr: "колело" },
      { en: "motorcycle", bg: "mototsiklet", cyr: "мотоциклет" },
      { en: "truck", bg: "kamion", cyr: "камион" },
      { en: "taxi", bg: "taksi", cyr: "такси" },
      { en: "tram", bg: "tramvay", cyr: "трамвай" },
      { en: "metro", bg: "metro", cyr: "метро" },
      { en: "tire", bg: "guma", cyr: "гума" },
      { en: "engine", bg: "dvigatel", cyr: "двигател" },
      { en: "ticket", bg: "bilet", cyr: "билет" },
      { en: "speed", bg: "skorost", cyr: "скорост" },
      { en: "fuel", bg: "gorivo", cyr: "гориво" },
      { en: "to drive", bg: "karam", cyr: "карам" },
      { en: "to fly", bg: "letya", cyr: "летя" },
      { en: "to travel", bg: "patuvam", cyr: "пътувам" },
      { en: "trip", bg: "patuvane", cyr: "пътуване" },
      { en: "seat", bg: "sedalka", cyr: "седалка" },
      { en: "stop", bg: "spirka", cyr: "спирка" },
      { en: "to park", bg: "parkiram", cyr: "паркирам" },
      { en: "traffic light", bg: "svetofar", cyr: "светофар" },
      { en: "highway", bg: "magistrala", cyr: "магистрала" },
      { en: "road", bg: "pat", cyr: "път" },
    ],
  },
  {
    id: "money",
    name: "Money & banking",
    emoji: "💰",
    hue: 46,
    words: [
      { en: "money", bg: "pari", cyr: "пари" },
      { en: "price", bg: "tsena", cyr: "цена" },
      { en: "bank", bg: "banka", cyr: "банка" },
      { en: "coin", bg: "moneta", cyr: "монета" },
      { en: "banknote", bg: "banknota", cyr: "банкнота" },
      { en: "credit card", bg: "kreditna karta", cyr: "кредитна карта" },
      { en: "account", bg: "smetka", cyr: "сметка" },
      { en: "to save", bg: "spestyavam", cyr: "спестявам" },
      { en: "to spend", bg: "harcha", cyr: "харча" },
      { en: "to owe", bg: "dalzha", cyr: "дължа" },
      { en: "salary", bg: "zaplata", cyr: "заплата" },
      { en: "tax", bg: "danak", cyr: "данък" },
      { en: "debt", bg: "dalg", cyr: "дълг" },
      { en: "loan", bg: "zaem", cyr: "заем" },
      { en: "interest", bg: "lihva", cyr: "лихва" },
      { en: "free", bg: "bezplatno", cyr: "безплатно" },
      { en: "change", bg: "reste", cyr: "ресто" },
      { en: "wallet", bg: "portfeyl", cyr: "портфейл" },
      { en: "exchange", bg: "obmyana", cyr: "обмяна" },
      { en: "to cost", bg: "struva", cyr: "струва" },
      { en: "currency", bg: "valuta", cyr: "валута" },
      { en: "cash", bg: "v broy", cyr: "в брой" },
      { en: "cheap", bg: "evtino", cyr: "евтино" },
      { en: "expensive", bg: "skapo", cyr: "скъпо" },
      { en: "to earn", bg: "pecheli", cyr: "печеля" },
      { en: "to pay", bg: "plashtam", cyr: "плащам" },
      { en: "to buy", bg: "kupuvam", cyr: "купувам" },
    ],
  },
  {
    id: "calendar",
    name: "Calendar & months",
    emoji: "📅",
    hue: 145,
    words: [
      { en: "calendar", bg: "kalendar", cyr: "календар" },
      { en: "Monday", bg: "ponedelnik", cyr: "понеделник" },
      { en: "Tuesday", bg: "vtornik", cyr: "вторник" },
      { en: "Wednesday", bg: "sryada", cyr: "сряда" },
      { en: "Thursday", bg: "chetvartak", cyr: "четвъртък" },
      { en: "Friday", bg: "petak", cyr: "петък" },
      { en: "Saturday", bg: "sabota", cyr: "събота" },
      { en: "Sunday", bg: "nedelya", cyr: "неделя" },
      { en: "January", bg: "yanuari", cyr: "януари" },
      { en: "February", bg: "fevruari", cyr: "февруари" },
      { en: "March", bg: "mart", cyr: "март" },
      { en: "April", bg: "april", cyr: "април" },
      { en: "May", bg: "may", cyr: "май" },
      { en: "June", bg: "yuni", cyr: "юни" },
      { en: "July", bg: "yuli", cyr: "юли" },
      { en: "August", bg: "avgust", cyr: "август" },
      { en: "September", bg: "septemvri", cyr: "септември" },
      { en: "October", bg: "oktomvri", cyr: "октомври" },
      { en: "November", bg: "noemvri", cyr: "ноември" },
      { en: "December", bg: "dekemvri", cyr: "декември" },
      { en: "spring", bg: "prolet", cyr: "пролет" },
      { en: "summer", bg: "lyato", cyr: "лято" },
      { en: "autumn", bg: "esen", cyr: "есен" },
      { en: "winter", bg: "zima", cyr: "зима" },
      { en: "weekend", bg: "uikend", cyr: "уикенд" },
      { en: "holiday", bg: "praznik", cyr: "празник" },
      { en: "date", bg: "data", cyr: "дата" },
    ],
  },
  {
    id: "clothing",
    name: "Clothing & accessories",
    emoji: "👕",
    hue: 332,
    words: [
      { en: "clothes", bg: "drehi", cyr: "дрехи" },
      { en: "t-shirt", bg: "teniska", cyr: "тениска" },
      { en: "jeans", bg: "danki", cyr: "дънки" },
      { en: "skirt", bg: "pola", cyr: "пола" },
      { en: "jacket", bg: "yake", cyr: "яке" },
      { en: "coat", bg: "palto", cyr: "палто" },
      { en: "sweater", bg: "pulover", cyr: "пуловер" },
      { en: "boots", bg: "botushi", cyr: "ботуши" },
      { en: "socks", bg: "chorapi", cyr: "чорапи" },
      { en: "gloves", bg: "rakavitsi", cyr: "ръкавици" },
      { en: "scarf", bg: "shal", cyr: "шал" },
      { en: "belt", bg: "kolan", cyr: "колан" },
      { en: "tie", bg: "vratovrazka", cyr: "вратовръзка" },
      { en: "glasses", bg: "ochila", cyr: "очила" },
      { en: "ring", bg: "prasten", cyr: "пръстен" },
      { en: "watch", bg: "chasovnik", cyr: "часовник" },
      { en: "handbag", bg: "chanta", cyr: "чанта" },
      { en: "umbrella", bg: "chadar", cyr: "чадър" },
      { en: "pocket", bg: "dzhob", cyr: "джоб" },
      { en: "to wear", bg: "nosya", cyr: "нося" },
      { en: "underwear", bg: "belyo", cyr: "бельо" },
      { en: "shirt", bg: "riza", cyr: "риза" },
      { en: "trousers", bg: "pantalon", cyr: "панталон" },
      { en: "dress", bg: "roklya", cyr: "рокля" },
      { en: "shoes", bg: "obuvki", cyr: "обувки" },
      { en: "hat", bg: "shapka", cyr: "шапка" },
      { en: "size", bg: "razmer", cyr: "размер" },
    ],
  },
  {
    id: "materials",
    name: "Materials & substances",
    emoji: "🪵",
    hue: 36,
    words: [
      { en: "wood", bg: "darvo", cyr: "дърво" },
      { en: "metal", bg: "metal", cyr: "метал" },
      { en: "iron", bg: "zhelyazo", cyr: "желязо" },
      { en: "gold", bg: "zlato", cyr: "злато" },
      { en: "silver", bg: "srebro", cyr: "сребро" },
      { en: "glass", bg: "staklo", cyr: "стъкло" },
      { en: "plastic", bg: "plastmasa", cyr: "пластмаса" },
      { en: "paper", bg: "hartiya", cyr: "хартия" },
      { en: "stone", bg: "kamak", cyr: "камък" },
      { en: "sand", bg: "pyasak", cyr: "пясък" },
      { en: "air", bg: "vazduh", cyr: "въздух" },
      { en: "gas", bg: "gaz", cyr: "газ" },
      { en: "oil / petroleum", bg: "neft", cyr: "нефт" },
      { en: "coal", bg: "vaglishta", cyr: "въглища" },
      { en: "leather", bg: "kozha", cyr: "кожа" },
      { en: "cotton", bg: "pamuk", cyr: "памук" },
      { en: "wool", bg: "valna", cyr: "вълна" },
      { en: "rubber", bg: "guma", cyr: "гума" },
      { en: "clay", bg: "glina", cyr: "глина" },
      { en: "diamond", bg: "diamant", cyr: "диамант" },
      { en: "dust", bg: "prah", cyr: "прах" },
      { en: "smoke", bg: "dim", cyr: "дим" },
      { en: "water", bg: "voda", cyr: "вода" },
      { en: "fire", bg: "ogan", cyr: "огън" },
      { en: "ice", bg: "led", cyr: "лед" },
      { en: "salt", bg: "sol", cyr: "сол" },
      { en: "sugar", bg: "zahar", cyr: "захар" },
    ],
  },
  {
    id: "survival",
    name: "Survival phrases",
    emoji: "🆘",
    hue: 4,
    words: [
      { en: "do you speak English?", bg: "govorite li angliyski", cyr: "говорите ли английски" },
      { en: "I don't speak Bulgarian", bg: "ne govorya balgarski", cyr: "не говоря български" },
      { en: "can you help me?", bg: "mozhete li da mi pomognete", cyr: "можете ли да ми помогнете" },
      { en: "where is the toilet?", bg: "kade e toaletnata", cyr: "къде е тоалетната" },
      { en: "I would like", bg: "bih iskal", cyr: "бих искал" },
      { en: "I'm lost", bg: "izgubih se", cyr: "изгубих се" },
      { en: "I need a doctor", bg: "tryabva mi lekar", cyr: "трябва ми лекар" },
      { en: "what does it mean?", bg: "kakvo oznachava", cyr: "какво означава" },
      { en: "speak slowly", bg: "govorete bavno", cyr: "говорете бавно" },
      { en: "I understand", bg: "razbiram", cyr: "разбирам" },
      { en: "repeat please", bg: "povtorete molya", cyr: "повторете моля" },
      { en: "how do you say?", bg: "kak se kazva", cyr: "как се казва" },
      { en: "it's not working", bg: "ne raboti", cyr: "не работи" },
      { en: "leave me alone", bg: "ostavete me na mira", cyr: "оставете ме на мира" },
      { en: "help me please", bg: "pomognete mi molya", cyr: "помогнете ми моля" },
      { en: "one moment", bg: "edin moment", cyr: "един момент" },
      { en: "bon appetit", bg: "dobar apetit", cyr: "добър апетит" },
      { en: "see you later", bg: "do skoro", cyr: "до скоро" },
      { en: "welcome", bg: "dobre doshli", cyr: "добре дошли" },
      { en: "it doesn't matter", bg: "nyama znachenie", cyr: "няма значение" },
      { en: "with pleasure", bg: "s udovolstvie", cyr: "с удоволствие" },
      { en: "I agree", bg: "saglasen sam", cyr: "съгласен съм" },
      { en: "happy birthday", bg: "chestit rozhden den", cyr: "честит рожден ден" },
      { en: "congratulations", bg: "chestito", cyr: "честито" },
      { en: "take care", bg: "pazi se", cyr: "пази се" },
    ],
  },
  {
    id: "music",
    name: "Music & arts",
    emoji: "🎵",
    hue: 300,
    words: [
      { en: "music", bg: "muzika", cyr: "музика" },
      { en: "song", bg: "pesen", cyr: "песен" },
      { en: "art", bg: "izkustvo", cyr: "изкуство" },
      { en: "painting", bg: "kartina", cyr: "картина" },
      { en: "drawing", bg: "risunka", cyr: "рисунка" },
      { en: "brush", bg: "chetka", cyr: "четка" },
      { en: "stage", bg: "stsena", cyr: "сцена" },
      { en: "concert", bg: "kontsert", cyr: "концерт" },
      { en: "band", bg: "grupa", cyr: "група" },
      { en: "instrument", bg: "instrument", cyr: "инструмент" },
      { en: "piano", bg: "piano", cyr: "пиано" },
      { en: "violin", bg: "tsigulka", cyr: "цигулка" },
      { en: "drum", bg: "baraban", cyr: "барабан" },
      { en: "flute", bg: "fleyta", cyr: "флейта" },
      { en: "note", bg: "nota", cyr: "нота" },
      { en: "voice", bg: "glas", cyr: "глас" },
      { en: "dance", bg: "tants", cyr: "танц" },
      { en: "author", bg: "avtor", cyr: "автор" },
      { en: "poet", bg: "poet", cyr: "поет" },
      { en: "novel", bg: "roman", cyr: "роман" },
      { en: "gallery", bg: "galeriya", cyr: "галерия" },
      { en: "sculpture", bg: "skulptura", cyr: "скулптура" },
      { en: "to sing", bg: "peya", cyr: "пея" },
      { en: "color", bg: "tsvyat", cyr: "цвят" },
      { en: "theater", bg: "teatar", cyr: "театър" },
      { en: "actor", bg: "aktyor", cyr: "актьор" },
    ],
  },
  {
    id: "garden",
    name: "Garden & plants",
    emoji: "🌱",
    hue: 110,
    words: [
      { en: "plant", bg: "rastenie", cyr: "растение" },
      { en: "flower", bg: "tsvete", cyr: "цвете" },
      { en: "tree", bg: "darvo", cyr: "дърво" },
      { en: "grass", bg: "treva", cyr: "трева" },
      { en: "leaf", bg: "list", cyr: "лист" },
      { en: "root", bg: "koren", cyr: "корен" },
      { en: "seed", bg: "seme", cyr: "семе" },
      { en: "branch", bg: "klon", cyr: "клон" },
      { en: "garden", bg: "gradina", cyr: "градина" },
      { en: "rose", bg: "roza", cyr: "роза" },
      { en: "tulip", bg: "lale", cyr: "лале" },
      { en: "bush", bg: "hrast", cyr: "храст" },
      { en: "to grow", bg: "rasta", cyr: "раста" },
      { en: "to plant", bg: "sadya", cyr: "садя" },
      { en: "to water", bg: "polivam", cyr: "поливам" },
      { en: "fruit", bg: "plod", cyr: "плод" },
      { en: "vegetable", bg: "zelenchuk", cyr: "зеленчук" },
      { en: "weed", bg: "plevel", cyr: "плевел" },
      { en: "flowerpot", bg: "saksiya", cyr: "саксия" },
      { en: "harvest", bg: "rekolta", cyr: "реколта" },
      { en: "field", bg: "niva", cyr: "нива" },
      { en: "farm", bg: "ferma", cyr: "ферма" },
      { en: "vineyard", bg: "loze", cyr: "лозе" },
      { en: "wheat", bg: "zhito", cyr: "жито" },
      { en: "corn", bg: "tsarevitsa", cyr: "царевица" },
      { en: "mushroom", bg: "gaba", cyr: "гъба" },
      { en: "soil", bg: "pochva", cyr: "почва" },
    ],
  },
  {
    id: "health",
    name: "Health & medicine",
    emoji: "💊",
    hue: 0,
    words: [
      { en: "health", bg: "zdrave", cyr: "здраве" },
      { en: "dentist", bg: "zabolekar", cyr: "зъболекар" },
      { en: "pill", bg: "hapche", cyr: "хапче" },
      { en: "injection", bg: "injektsiya", cyr: "инжекция" },
      { en: "fever", bg: "treska", cyr: "треска" },
      { en: "cough", bg: "kashlitsa", cyr: "кашлица" },
      { en: "a cold", bg: "nastinka", cyr: "настинка" },
      { en: "flu", bg: "grip", cyr: "грип" },
      { en: "headache", bg: "glavobolie", cyr: "главоболие" },
      { en: "wound", bg: "rana", cyr: "рана" },
      { en: "to cure", bg: "lekuvam", cyr: "лекувам" },
      { en: "to rest", bg: "pochivam", cyr: "почивам" },
      { en: "to breathe", bg: "disham", cyr: "дишам" },
      { en: "bandage", bg: "bint", cyr: "бинт" },
      { en: "allergy", bg: "alergiya", cyr: "алергия" },
      { en: "vaccine", bg: "vaksina", cyr: "ваксина" },
      { en: "patient", bg: "patsient", cyr: "пациент" },
      { en: "examination", bg: "pregled", cyr: "преглед" },
      { en: "ambulance", bg: "lineyka", cyr: "линейка" },
      { en: "toothache", bg: "zabobol", cyr: "зъбобол" },
      { en: "medicine", bg: "lekarstvo", cyr: "лекарство" },
      { en: "hospital", bg: "bolnitsa", cyr: "болница" },
      { en: "pharmacy", bg: "apteka", cyr: "аптека" },
      { en: "pain", bg: "bolka", cyr: "болка" },
      { en: "healthy", bg: "zdrav", cyr: "здрав" },
      { en: "sick", bg: "bolen", cyr: "болен" },
    ],
  },
  {
    id: "office",
    name: "Office & business",
    emoji: "🏢",
    hue: 216,
    words: [
      { en: "office", bg: "ofis", cyr: "офис" },
      { en: "company", bg: "firma", cyr: "фирма" },
      { en: "meeting", bg: "sreshta", cyr: "среща" },
      { en: "colleague", bg: "kolega", cyr: "колега" },
      { en: "employee", bg: "sluzhitel", cyr: "служител" },
      { en: "contract", bg: "dogovor", cyr: "договор" },
      { en: "project", bg: "proekt", cyr: "проект" },
      { en: "deadline", bg: "krayen srok", cyr: "краен срок" },
      { en: "report", bg: "doklad", cyr: "доклад" },
      { en: "document", bg: "dokument", cyr: "документ" },
      { en: "printer", bg: "printer", cyr: "принтер" },
      { en: "desk", bg: "byuro", cyr: "бюро" },
      { en: "to sign", bg: "podpisvam", cyr: "подписвам" },
      { en: "signature", bg: "podpis", cyr: "подпис" },
      { en: "profit", bg: "pechalba", cyr: "печалба" },
      { en: "customer", bg: "klient", cyr: "клиент" },
      { en: "product", bg: "produkt", cyr: "продукт" },
      { en: "service", bg: "usluga", cyr: "услуга" },
      { en: "to manage", bg: "upravlyavam", cyr: "управлявам" },
      { en: "team", bg: "ekip", cyr: "екип" },
      { en: "goal", bg: "tsel", cyr: "цел" },
      { en: "plan", bg: "plan", cyr: "план" },
      { en: "idea", bg: "ideya", cyr: "идея" },
      { en: "success", bg: "uspeh", cyr: "успех" },
      { en: "boss", bg: "shef", cyr: "шеф" },
      { en: "deal", bg: "sdelka", cyr: "сделка" },
      { en: "schedule", bg: "grafik", cyr: "график" },
    ],
  },
  {
    id: "holidays",
    name: "Holidays & celebrations",
    emoji: "🎉",
    hue: 318,
    words: [
      { en: "holiday", bg: "praznik", cyr: "празник" },
      { en: "birthday", bg: "rozhden den", cyr: "рожден ден" },
      { en: "party", bg: "parti", cyr: "парти" },
      { en: "Christmas", bg: "Koleda", cyr: "Коледа" },
      { en: "Easter", bg: "Velikden", cyr: "Великден" },
      { en: "New Year", bg: "Nova godina", cyr: "Нова година" },
      { en: "celebration", bg: "praznuvane", cyr: "празнуване" },
      { en: "to celebrate", bg: "praznuvam", cyr: "празнувам" },
      { en: "guest", bg: "gost", cyr: "гост" },
      { en: "cake", bg: "torta", cyr: "торта" },
      { en: "candle", bg: "svesht", cyr: "свещ" },
      { en: "balloon", bg: "balon", cyr: "балон" },
      { en: "fireworks", bg: "foyerverk", cyr: "фойерверк" },
      { en: "wedding", bg: "svatba", cyr: "сватба" },
      { en: "to invite", bg: "kanya", cyr: "каня" },
      { en: "invitation", bg: "pokana", cyr: "покана" },
      { en: "surprise", bg: "iznenada", cyr: "изненада" },
      { en: "toast", bg: "nazdravitsa", cyr: "наздравица" },
      { en: "tradition", bg: "traditsiya", cyr: "традиция" },
      { en: "name day", bg: "imen den", cyr: "имен ден" },
      { en: "decoration", bg: "ukrasa", cyr: "украса" },
      { en: "champagne", bg: "shampansko", cyr: "шампанско" },
      { en: "anniversary", bg: "godishnina", cyr: "годишнина" },
      { en: "flag", bg: "zname", cyr: "знаме" },
      { en: "gift", bg: "podarak", cyr: "подарък" },
      { en: "to dance", bg: "tantsuvam", cyr: "танцувам" },
    ],
  },
  {
    id: "verbs2",
    name: "More verbs",
    emoji: "🤸",
    hue: 166,
    words: [
      { en: "to sell", bg: "prodavam", cyr: "продавам" },
      { en: "to ask", bg: "pitam", cyr: "питам" },
      { en: "to answer", bg: "otgovaryam", cyr: "отговарям" },
      { en: "to call", bg: "vikam", cyr: "викам" },
      { en: "to find", bg: "namiram", cyr: "намирам" },
      { en: "to lose", bg: "zagubvam", cyr: "загубвам" },
      { en: "to put", bg: "slagam", cyr: "слагам" },
      { en: "to close", bg: "zatvaryam", cyr: "затварям" },
      { en: "to begin", bg: "zapochvam", cyr: "започвам" },
      { en: "to finish", bg: "zavarshvam", cyr: "завършвам" },
      { en: "to stop", bg: "spiram", cyr: "спирам" },
      { en: "to continue", bg: "prodalzhavam", cyr: "продължавам" },
      { en: "to change", bg: "promenyam", cyr: "променям" },
      { en: "to use", bg: "izpolzvam", cyr: "използвам" },
      { en: "to need", bg: "tryabva", cyr: "трябва" },
      { en: "to remember", bg: "pomnya", cyr: "помня" },
      { en: "to forget", bg: "zabravyam", cyr: "забравям" },
      { en: "to believe", bg: "vyarvam", cyr: "вярвам" },
      { en: "to hope", bg: "nadyavam se", cyr: "надявам се" },
      { en: "to meet", bg: "sreshtam", cyr: "срещам" },
      { en: "to show", bg: "pokazvam", cyr: "показвам" },
      { en: "to follow", bg: "sledvam", cyr: "следвам" },
      { en: "to choose", bg: "izbiram", cyr: "избирам" },
      { en: "to send", bg: "izprashtam", cyr: "изпращам" },
      { en: "to receive", bg: "poluchavam", cyr: "получавам" },
      { en: "to build", bg: "stroya", cyr: "строя" },
      { en: "to break", bg: "chupya", cyr: "чупя" },
    ],
  },
  {
    id: "produce",
    name: "Fruits & vegetables",
    emoji: "🍎",
    hue: 100,
    words: [
      { en: "apple", bg: "yabalka", cyr: "ябълка" },
      { en: "pear", bg: "krusha", cyr: "круша" },
      { en: "grapes", bg: "grozde", cyr: "грозде" },
      { en: "strawberry", bg: "yagoda", cyr: "ягода" },
      { en: "cherry", bg: "cheresha", cyr: "череша" },
      { en: "peach", bg: "praskova", cyr: "праскова" },
      { en: "plum", bg: "sliva", cyr: "слива" },
      { en: "watermelon", bg: "dinya", cyr: "диня" },
      { en: "melon", bg: "papesh", cyr: "пъпеш" },
      { en: "orange", bg: "portokal", cyr: "портокал" },
      { en: "lemon", bg: "limon", cyr: "лимон" },
      { en: "carrot", bg: "morkov", cyr: "морков" },
      { en: "onion", bg: "luk", cyr: "лук" },
      { en: "garlic", bg: "chesan", cyr: "чесън" },
      { en: "pepper", bg: "chushka", cyr: "чушка" },
      { en: "cabbage", bg: "zele", cyr: "зеле" },
      { en: "bean", bg: "bob", cyr: "боб" },
      { en: "pea", bg: "grah", cyr: "грах" },
      { en: "pumpkin", bg: "tikva", cyr: "тиква" },
      { en: "eggplant", bg: "patladzhan", cyr: "патладжан" },
      { en: "spinach", bg: "spanak", cyr: "спанак" },
      { en: "banana", bg: "banan", cyr: "банан" },
      { en: "tomato", bg: "domat", cyr: "домат" },
      { en: "cucumber", bg: "krastavitsa", cyr: "краставица" },
      { en: "potato", bg: "kartof", cyr: "картоф" },
      { en: "fruit", bg: "plod", cyr: "плод" },
      { en: "vegetable", bg: "zelenchuk", cyr: "зеленчук" },
    ],
  },
  {
    id: "drinks",
    name: "Drinks",
    emoji: "🥤",
    hue: 198,
    words: [
      { en: "water", bg: "voda", cyr: "вода" },
      { en: "coffee", bg: "kafe", cyr: "кафе" },
      { en: "tea", bg: "chay", cyr: "чай" },
      { en: "juice", bg: "sok", cyr: "сок" },
      { en: "beer", bg: "bira", cyr: "бира" },
      { en: "wine", bg: "vino", cyr: "вино" },
      { en: "milk", bg: "mlyako", cyr: "мляко" },
      { en: "rakia", bg: "rakiya", cyr: "ракия" },
      { en: "lemonade", bg: "limonada", cyr: "лимонада" },
      { en: "ayran", bg: "ayryan", cyr: "айрян" },
      { en: "mineral water", bg: "mineralna voda", cyr: "минерална вода" },
      { en: "hot chocolate", bg: "goresht shokolad", cyr: "горещ шоколад" },
      { en: "cocktail", bg: "kokteyl", cyr: "коктейл" },
      { en: "whiskey", bg: "uiski", cyr: "уиски" },
      { en: "vodka", bg: "vodka", cyr: "водка" },
      { en: "smoothie", bg: "smuti", cyr: "смути" },
      { en: "straw", bg: "slamka", cyr: "сламка" },
      { en: "sip", bg: "glatka", cyr: "глътка" },
      { en: "soft drink", bg: "bezalkoholno", cyr: "безалкохолно" },
      { en: "espresso", bg: "espreso", cyr: "еспресо" },
      { en: "glass", bg: "chasha", cyr: "чаша" },
      { en: "bottle", bg: "butilka", cyr: "бутилка" },
      { en: "cheers", bg: "nazdrave", cyr: "наздраве" },
      { en: "to drink", bg: "piya", cyr: "пия" },
      { en: "ice", bg: "led", cyr: "лед" },
      { en: "thirst", bg: "zhazhda", cyr: "жажда" },
    ],
  },
  {
    id: "personality",
    name: "Personality & character",
    emoji: "🧠",
    hue: 290,
    words: [
      { en: "kind", bg: "mil", cyr: "мил" },
      { en: "nice", bg: "priyaten", cyr: "приятен" },
      { en: "friendly", bg: "druzhelyuben", cyr: "дружелюбен" },
      { en: "funny", bg: "smeshen", cyr: "смешен" },
      { en: "serious", bg: "seriozen", cyr: "сериозен" },
      { en: "smart", bg: "umen", cyr: "умен" },
      { en: "stupid", bg: "glupav", cyr: "глупав" },
      { en: "brave", bg: "smel", cyr: "смел" },
      { en: "honest", bg: "chesten", cyr: "честен" },
      { en: "polite", bg: "uchtiv", cyr: "учтив" },
      { en: "rude", bg: "grub", cyr: "груб" },
      { en: "lazy", bg: "murzeliv", cyr: "мързелив" },
      { en: "hardworking", bg: "trudolyubiv", cyr: "трудолюбив" },
      { en: "generous", bg: "shtedar", cyr: "щедър" },
      { en: "selfish", bg: "egoist", cyr: "егоист" },
      { en: "patient", bg: "tarpeliv", cyr: "търпелив" },
      { en: "curious", bg: "lyubopiten", cyr: "любопитен" },
      { en: "quiet", bg: "tih", cyr: "тих" },
      { en: "loud", bg: "shumen", cyr: "шумен" },
      { en: "strict", bg: "strog", cyr: "строг" },
      { en: "gentle", bg: "nezhen", cyr: "нежен" },
      { en: "cheerful", bg: "vesel", cyr: "весел" },
      { en: "careful", bg: "vnimatelen", cyr: "внимателен" },
      { en: "crazy", bg: "lud", cyr: "луд" },
      { en: "wise", bg: "madar", cyr: "мъдър" },
      { en: "modest", bg: "skromen", cyr: "скромен" },
      { en: "character", bg: "harakter", cyr: "характер" },
    ],
  },
  {
    id: "sea",
    name: "Sea & beach",
    emoji: "🏖️",
    hue: 190,
    words: [
      { en: "sea", bg: "more", cyr: "море" },
      { en: "beach", bg: "plazh", cyr: "плаж" },
      { en: "sand", bg: "pyasak", cyr: "пясък" },
      { en: "wave", bg: "valna", cyr: "вълна" },
      { en: "sun", bg: "slantse", cyr: "слънце" },
      { en: "seashell", bg: "cherupka", cyr: "черупка" },
      { en: "swimsuit", bg: "bansky", cyr: "бански" },
      { en: "beach towel", bg: "havliya", cyr: "хавлия" },
      { en: "umbrella", bg: "chadar", cyr: "чадър" },
      { en: "boat", bg: "lodka", cyr: "лодка" },
      { en: "island", bg: "ostrov", cyr: "остров" },
      { en: "fish", bg: "riba", cyr: "риба" },
      { en: "crab", bg: "rak", cyr: "рак" },
      { en: "dolphin", bg: "delfin", cyr: "делфин" },
      { en: "shark", bg: "akula", cyr: "акула" },
      { en: "to swim", bg: "pluvam", cyr: "плувам" },
      { en: "to dive", bg: "gmurkam se", cyr: "гмуркам се" },
      { en: "coast", bg: "bryag", cyr: "бряг" },
      { en: "port", bg: "pristanishte", cyr: "пристанище" },
      { en: "lighthouse", bg: "far", cyr: "фар" },
      { en: "anchor", bg: "kotva", cyr: "котва" },
      { en: "sail", bg: "platno", cyr: "платно" },
      { en: "seagull", bg: "chayka", cyr: "чайка" },
      { en: "swimming", bg: "pluvane", cyr: "плуване" },
      { en: "deep", bg: "dalbok", cyr: "дълбок" },
      { en: "wet", bg: "mokar", cyr: "мокър" },
    ],
  },
  {
    id: "bathroom",
    name: "Bathroom & hygiene",
    emoji: "🚿",
    hue: 184,
    words: [
      { en: "bathroom", bg: "banya", cyr: "баня" },
      { en: "toilet", bg: "toaletna", cyr: "тоалетна" },
      { en: "shower", bg: "dush", cyr: "душ" },
      { en: "soap", bg: "sapun", cyr: "сапун" },
      { en: "toothbrush", bg: "chetka za zabi", cyr: "четка за зъби" },
      { en: "toothpaste", bg: "pasta za zabi", cyr: "паста за зъби" },
      { en: "shampoo", bg: "shampoan", cyr: "шампоан" },
      { en: "mirror", bg: "ogledalo", cyr: "огледало" },
      { en: "comb", bg: "greben", cyr: "гребен" },
      { en: "razor", bg: "brasnach", cyr: "бръснач" },
      { en: "perfume", bg: "parfyum", cyr: "парфюм" },
      { en: "to wash", bg: "mia", cyr: "мия" },
      { en: "to shave", bg: "brasna se", cyr: "бръсна се" },
      { en: "to clean", bg: "pochistvam", cyr: "почиствам" },
      { en: "tap", bg: "kran", cyr: "кран" },
      { en: "sink", bg: "mivka", cyr: "мивка" },
      { en: "bathtub", bg: "vana", cyr: "вана" },
      { en: "nail", bg: "nokat", cyr: "нокът" },
      { en: "to dry", bg: "susha", cyr: "суша" },
      { en: "smell", bg: "mirizma", cyr: "миризма" },
      { en: "clean", bg: "chist", cyr: "чист" },
      { en: "dirty", bg: "mrasen", cyr: "мръсен" },
      { en: "water", bg: "voda", cyr: "вода" },
      { en: "hair", bg: "kosa", cyr: "коса" },
      { en: "towel", bg: "karpa", cyr: "кърпа" },
      { en: "haircut", bg: "podstrigvane", cyr: "подстригване" },
    ],
  },
  {
    id: "bgfood",
    name: "Bulgarian specialties",
    emoji: "🥟",
    hue: 14,
    words: [
      { en: "cheese pastry", bg: "banitsa", cyr: "баница" },
      { en: "shepherd salad", bg: "shopska salata", cyr: "шопска салата" },
      { en: "cold cucumber soup", bg: "tarator", cyr: "таратор" },
      { en: "grilled mince roll", bg: "kebapche", cyr: "кебапче" },
      { en: "meatball", bg: "kyufte", cyr: "кюфте" },
      { en: "pepper relish", bg: "lyutenitsa", cyr: "лютеница" },
      { en: "white cheese", bg: "sirene", cyr: "сирене" },
      { en: "yellow cheese", bg: "kashkaval", cyr: "кашкавал" },
      { en: "fermented wheat drink", bg: "boza", cyr: "боза" },
      { en: "moussaka", bg: "musaka", cyr: "мусака" },
      { en: "stuffed vine leaves", bg: "sarmi", cyr: "сарми" },
      { en: "clay-pot stew", bg: "gyuvech", cyr: "гювеч" },
      { en: "fried dough", bg: "mekitsa", cyr: "мекица" },
      { en: "bread in warm milk", bg: "popara", cyr: "попара" },
      { en: "yogurt", bg: "kiselo mlyako", cyr: "кисело мляко" },
      { en: "dry sausage", bg: "lukanka", cyr: "луканка" },
      { en: "spicy sausage", bg: "sudzhuk", cyr: "суджук" },
      { en: "dried cured meat", bg: "pastarma", cyr: "пастърма" },
      { en: "baklava", bg: "baklava", cyr: "баклава" },
      { en: "halva", bg: "halva", cyr: "халва" },
      { en: "Easter bread", bg: "kozunak", cyr: "козунак" },
      { en: "tripe soup", bg: "shkembe", cyr: "шкембе" },
      { en: "bean soup", bg: "bob chorba", cyr: "боб чорба" },
      { en: "breaded cheese toast", bg: "printsesa", cyr: "принцеса" },
      { en: "rakia", bg: "rakiya", cyr: "ракия" },
      { en: "ayran", bg: "ayryan", cyr: "айрян" },
    ],
  },
  {
    id: "tools",
    name: "Tools & DIY",
    emoji: "🔧",
    hue: 40,
    words: [
      { en: "tool", bg: "sechivo", cyr: "сечиво" },
      { en: "hammer", bg: "chuk", cyr: "чук" },
      { en: "screw", bg: "vint", cyr: "винт" },
      { en: "screwdriver", bg: "otvertka", cyr: "отвертка" },
      { en: "saw", bg: "trion", cyr: "трион" },
      { en: "drill", bg: "bormashina", cyr: "бормашина" },
      { en: "wrench", bg: "gaechen klyuch", cyr: "гаечен ключ" },
      { en: "pliers", bg: "kleshti", cyr: "клещи" },
      { en: "scissors", bg: "nozhitsa", cyr: "ножица" },
      { en: "rope", bg: "vazhe", cyr: "въже" },
      { en: "chain", bg: "veriga", cyr: "верига" },
      { en: "ladder", bg: "stalba", cyr: "стълба" },
      { en: "glue", bg: "lepilo", cyr: "лепило" },
      { en: "tape", bg: "lepenka", cyr: "лепенка" },
      { en: "paint", bg: "boya", cyr: "боя" },
      { en: "box", bg: "kutiya", cyr: "кутия" },
      { en: "wire", bg: "zhitsa", cyr: "жица" },
      { en: "to fix", bg: "popravyam", cyr: "поправям" },
      { en: "machine", bg: "mashina", cyr: "машина" },
      { en: "knife", bg: "nozh", cyr: "нож" },
      { en: "brush", bg: "chetka", cyr: "четка" },
      { en: "battery", bg: "bateriya", cyr: "батерия" },
      { en: "metal", bg: "metal", cyr: "метал" },
      { en: "wood", bg: "darvo", cyr: "дърво" },
      { en: "nail", bg: "piron", cyr: "пирон" },
      { en: "to build", bg: "stroya", cyr: "строя" },
    ],
  },
  {
    id: "science",
    name: "Space & science",
    emoji: "🔬",
    hue: 250,
    words: [
      { en: "science", bg: "nauka", cyr: "наука" },
      { en: "space", bg: "kosmos", cyr: "космос" },
      { en: "planet", bg: "planeta", cyr: "планета" },
      { en: "universe", bg: "vselena", cyr: "вселена" },
      { en: "galaxy", bg: "galaktika", cyr: "галактика" },
      { en: "rocket", bg: "raketa", cyr: "ракета" },
      { en: "astronaut", bg: "kosmonavt", cyr: "космонавт" },
      { en: "gravity", bg: "gravitatsiya", cyr: "гравитация" },
      { en: "energy", bg: "energiya", cyr: "енергия" },
      { en: "atom", bg: "atom", cyr: "атом" },
      { en: "cell", bg: "kletka", cyr: "клетка" },
      { en: "experiment", bg: "eksperiment", cyr: "експеримент" },
      { en: "chemistry", bg: "himiya", cyr: "химия" },
      { en: "physics", bg: "fizika", cyr: "физика" },
      { en: "biology", bg: "biologiya", cyr: "биология" },
      { en: "mathematics", bg: "matematika", cyr: "математика" },
      { en: "theory", bg: "teoriya", cyr: "теория" },
      { en: "light", bg: "svetlina", cyr: "светлина" },
      { en: "liquid", bg: "technost", cyr: "течност" },
      { en: "solid", bg: "tvardo", cyr: "твърдо" },
      { en: "temperature", bg: "temperatura", cyr: "температура" },
      { en: "microscope", bg: "mikroskop", cyr: "микроскоп" },
      { en: "telescope", bg: "teleskop", cyr: "телескоп" },
      { en: "star", bg: "zvezda", cyr: "звезда" },
      { en: "moon", bg: "luna", cyr: "луна" },
      { en: "gas", bg: "gaz", cyr: "газ" },
      { en: "to discover", bg: "otkrivam", cyr: "откривам" },
    ],
  },
  {
    id: "hotel",
    name: "Hotel & accommodation",
    emoji: "🏨",
    hue: 206,
    words: [
      { en: "hotel", bg: "hotel", cyr: "хотел" },
      { en: "room", bg: "staya", cyr: "стая" },
      { en: "reception", bg: "retseptsiya", cyr: "рецепция" },
      { en: "key", bg: "klyuch", cyr: "ключ" },
      { en: "bed", bg: "leglo", cyr: "легло" },
      { en: "pillow", bg: "vazglavnitsa", cyr: "възглавница" },
      { en: "blanket", bg: "odeyalo", cyr: "одеяло" },
      { en: "sheet", bg: "charshaf", cyr: "чаршаф" },
      { en: "breakfast", bg: "zakuska", cyr: "закуска" },
      { en: "booking", bg: "rezervatsiya", cyr: "резервация" },
      { en: "check-in", bg: "nastanyavane", cyr: "настаняване" },
      { en: "check-out", bg: "napuskane", cyr: "напускане" },
      { en: "floor", bg: "etazh", cyr: "етаж" },
      { en: "elevator", bg: "asansyor", cyr: "асансьор" },
      { en: "luggage", bg: "bagazh", cyr: "багаж" },
      { en: "suitcase", bg: "kufar", cyr: "куфар" },
      { en: "guest", bg: "gost", cyr: "гост" },
      { en: "single room", bg: "edinichna staya", cyr: "единична стая" },
      { en: "double room", bg: "dvoyna staya", cyr: "двойна стая" },
      { en: "night", bg: "nosht", cyr: "нощ" },
      { en: "view", bg: "gledka", cyr: "гледка" },
      { en: "balcony", bg: "balkon", cyr: "балкон" },
      { en: "air conditioning", bg: "klimatik", cyr: "климатик" },
      { en: "safe", bg: "seyf", cyr: "сейф" },
      { en: "to stay", bg: "otsyadam", cyr: "отсядам" },
      { en: "towel", bg: "karpa", cyr: "кърпа" },
    ],
  },
  {
    id: "airport",
    name: "Airport & flying",
    emoji: "🛫",
    hue: 202,
    words: [
      { en: "airport", bg: "letishte", cyr: "летище" },
      { en: "plane", bg: "samolet", cyr: "самолет" },
      { en: "flight", bg: "polet", cyr: "полет" },
      { en: "ticket", bg: "bilet", cyr: "билет" },
      { en: "passport", bg: "pasport", cyr: "паспорт" },
      { en: "boarding pass", bg: "bordna karta", cyr: "бордна карта" },
      { en: "gate", bg: "izhod", cyr: "изход" },
      { en: "luggage", bg: "bagazh", cyr: "багаж" },
      { en: "suitcase", bg: "kufar", cyr: "куфар" },
      { en: "customs", bg: "mitnitsa", cyr: "митница" },
      { en: "security", bg: "ohrana", cyr: "охрана" },
      { en: "departure", bg: "zaminavane", cyr: "заминаване" },
      { en: "arrival", bg: "pristigane", cyr: "пристигане" },
      { en: "delay", bg: "zakasnenie", cyr: "закъснение" },
      { en: "pilot", bg: "pilot", cyr: "пилот" },
      { en: "crew", bg: "ekipazh", cyr: "екипаж" },
      { en: "seat", bg: "myasto", cyr: "място" },
      { en: "aisle", bg: "pateka", cyr: "пътека" },
      { en: "takeoff", bg: "izlitane", cyr: "излитане" },
      { en: "landing", bg: "katsane", cyr: "кацане" },
      { en: "to land", bg: "katsam", cyr: "кацам" },
      { en: "to take off", bg: "izlitam", cyr: "излитам" },
      { en: "terminal", bg: "terminal", cyr: "терминал" },
      { en: "duty free", bg: "bezmiten", cyr: "безмитен" },
      { en: "direct flight", bg: "direkten polet", cyr: "директен полет" },
      { en: "window", bg: "prozorets", cyr: "прозорец" },
    ],
  },
  {
    id: "ordinals",
    name: "Time & ordinals",
    emoji: "⏱️",
    hue: 270,
    words: [
      { en: "first", bg: "parvi", cyr: "първи" },
      { en: "second", bg: "vtori", cyr: "втори" },
      { en: "third", bg: "treti", cyr: "трети" },
      { en: "fourth", bg: "chetvarti", cyr: "четвърти" },
      { en: "fifth", bg: "peti", cyr: "пети" },
      { en: "last", bg: "posleden", cyr: "последен" },
      { en: "a second", bg: "sekunda", cyr: "секунда" },
      { en: "half", bg: "polovina", cyr: "половина" },
      { en: "quarter", bg: "chetvart", cyr: "четвърт" },
      { en: "early", bg: "rano", cyr: "рано" },
      { en: "late", bg: "kasno", cyr: "късно" },
      { en: "soon", bg: "skoro", cyr: "скоро" },
      { en: "moment", bg: "moment", cyr: "момент" },
      { en: "midday", bg: "pladne", cyr: "пладне" },
      { en: "midnight", bg: "polunosht", cyr: "полунощ" },
      { en: "past", bg: "minalo", cyr: "минало" },
      { en: "future", bg: "badeshte", cyr: "бъдеще" },
      { en: "present", bg: "nastoyashte", cyr: "настояще" },
      { en: "century", bg: "vek", cyr: "век" },
      { en: "decade", bg: "desetiletie", cyr: "десетилетие" },
      { en: "once", bg: "vednazh", cyr: "веднъж" },
      { en: "twice", bg: "dva pati", cyr: "два пъти" },
      { en: "daily", bg: "vsekidnevno", cyr: "всекидневно" },
      { en: "hour", bg: "chas", cyr: "час" },
      { en: "minute", bg: "minuta", cyr: "минута" },
      { en: "o'clock", bg: "chasa", cyr: "часа" },
    ],
  },
  {
    id: "routine",
    name: "Daily routine",
    emoji: "🌅",
    hue: 176,
    words: [
      { en: "to wake up", bg: "sabuzhdam se", cyr: "събуждам се" },
      { en: "to get up", bg: "stavam", cyr: "ставам" },
      { en: "to wash", bg: "mia se", cyr: "мия се" },
      { en: "to brush teeth", bg: "mia zabite", cyr: "мия зъбите" },
      { en: "to get dressed", bg: "oblicham se", cyr: "обличам се" },
      { en: "to have breakfast", bg: "zakusvam", cyr: "закусвам" },
      { en: "to go to work", bg: "otivam na rabota", cyr: "отивам на работа" },
      { en: "to have lunch", bg: "obyadvam", cyr: "обядвам" },
      { en: "to come home", bg: "vrashtam se", cyr: "връщам се" },
      { en: "to have dinner", bg: "vecheryam", cyr: "вечерям" },
      { en: "to watch TV", bg: "gledam televiziya", cyr: "гледам телевизия" },
      { en: "to go to bed", bg: "lyagam si", cyr: "лягам си" },
      { en: "to dream", bg: "sanuvam", cyr: "сънувам" },
      { en: "to shower", bg: "vzemam dush", cyr: "взимам душ" },
      { en: "routine", bg: "ezhednevie", cyr: "ежедневие" },
      { en: "to hurry", bg: "barzam", cyr: "бързам" },
      { en: "to relax", bg: "otpuskam se", cyr: "отпускам се" },
      { en: "to clean", bg: "chistya", cyr: "чистя" },
      { en: "to shop", bg: "pazaruvam", cyr: "пазарувам" },
      { en: "to rest", bg: "pochivam", cyr: "почивам" },
      { en: "to cook", bg: "gotvya", cyr: "готвя" },
      { en: "to sleep", bg: "spya", cyr: "спя" },
      { en: "to read", bg: "cheta", cyr: "чета" },
      { en: "to work", bg: "rabotya", cyr: "работя" },
      { en: "morning", bg: "sutrin", cyr: "сутрин" },
      { en: "early", bg: "rano", cyr: "рано" },
    ],
  },
  {
    id: "countries",
    name: "Countries & nations",
    emoji: "🌍",
    hue: 214,
    words: [
      { en: "Bulgaria", bg: "Balgariya", cyr: "България" },
      { en: "England", bg: "Angliya", cyr: "Англия" },
      { en: "America", bg: "Amerika", cyr: "Америка" },
      { en: "Germany", bg: "Germaniya", cyr: "Германия" },
      { en: "France", bg: "Frantsiya", cyr: "Франция" },
      { en: "Spain", bg: "Ispaniya", cyr: "Испания" },
      { en: "Italy", bg: "Italiya", cyr: "Италия" },
      { en: "Greece", bg: "Gartsiya", cyr: "Гърция" },
      { en: "Turkey", bg: "Turtsiya", cyr: "Турция" },
      { en: "Russia", bg: "Rusiya", cyr: "Русия" },
      { en: "Romania", bg: "Rumaniya", cyr: "Румъния" },
      { en: "Serbia", bg: "Sarbiya", cyr: "Сърбия" },
      { en: "country", bg: "strana", cyr: "страна" },
      { en: "nation", bg: "natsiya", cyr: "нация" },
      { en: "foreigner", bg: "chuzhdenets", cyr: "чужденец" },
      { en: "capital", bg: "stolitsa", cyr: "столица" },
      { en: "flag", bg: "zname", cyr: "знаме" },
      { en: "nationality", bg: "natsionalnost", cyr: "националност" },
      { en: "Europe", bg: "Evropa", cyr: "Европа" },
      { en: "China", bg: "Kitay", cyr: "Китай" },
      { en: "Japan", bg: "Yaponiya", cyr: "Япония" },
      { en: "abroad", bg: "chuzhbina", cyr: "чужбина" },
      { en: "citizen", bg: "grazhdanin", cyr: "гражданин" },
      { en: "world", bg: "svyat", cyr: "свят" },
      { en: "English", bg: "angliyski", cyr: "английски" },
      { en: "Bulgarian", bg: "balgarski", cyr: "български" },
    ],
  },
  {
    id: "cleaning",
    name: "Cleaning & chores",
    emoji: "🧹",
    hue: 168,
    words: [
      { en: "to tidy", bg: "raztrebvam", cyr: "разтребвам" },
      { en: "to do laundry", bg: "peria", cyr: "пера" },
      { en: "laundry", bg: "prane", cyr: "пране" },
      { en: "to iron", bg: "gladya", cyr: "гладя" },
      { en: "to sweep", bg: "meta", cyr: "мета" },
      { en: "vacuum cleaner", bg: "prahosmukachka", cyr: "прахосмукачка" },
      { en: "broom", bg: "metla", cyr: "метла" },
      { en: "bucket", bg: "kofa", cyr: "кофа" },
      { en: "sponge", bg: "gaba", cyr: "гъба" },
      { en: "soap", bg: "sapun", cyr: "сапун" },
      { en: "dust", bg: "prah", cyr: "прах" },
      { en: "garbage", bg: "boklyuk", cyr: "боклук" },
      { en: "trash can", bg: "kosche", cyr: "кошче" },
      { en: "to throw away", bg: "izhvarlyam", cyr: "изхвърлям" },
      { en: "to dry", bg: "susha", cyr: "суша" },
      { en: "mop", bg: "mop", cyr: "моп" },
      { en: "detergent", bg: "preparat", cyr: "препарат" },
      { en: "to wipe", bg: "barsha", cyr: "бърша" },
      { en: "order", bg: "red", cyr: "ред" },
      { en: "mess", bg: "bezredie", cyr: "безредие" },
      { en: "chore", bg: "zadalzhenie", cyr: "задължение" },
      { en: "clean", bg: "chist", cyr: "чист" },
      { en: "dirty", bg: "mrasen", cyr: "мръсен" },
      { en: "to fold", bg: "sgavam", cyr: "сгъвам" },
      { en: "to organize", bg: "organiziram", cyr: "организирам" },
      { en: "to wash dishes", bg: "mia chiniite", cyr: "мия чиниите" },
    ],
  },
  {
    id: "wildlife",
    name: "Wild animals",
    emoji: "🦁",
    hue: 32,
    words: [
      { en: "tiger", bg: "tigar", cyr: "тигър" },
      { en: "giraffe", bg: "zhiraf", cyr: "жираф" },
      { en: "zebra", bg: "zebra", cyr: "зебра" },
      { en: "crocodile", bg: "krokodil", cyr: "крокодил" },
      { en: "hippo", bg: "hipopotam", cyr: "хипопотам" },
      { en: "rhino", bg: "nosorog", cyr: "носорог" },
      { en: "kangaroo", bg: "kenguru", cyr: "кенгуру" },
      { en: "penguin", bg: "pingvin", cyr: "пингвин" },
      { en: "owl", bg: "buhal", cyr: "бухал" },
      { en: "eagle", bg: "orel", cyr: "орел" },
      { en: "parrot", bg: "papagal", cyr: "папагал" },
      { en: "snail", bg: "ohlyuv", cyr: "охлюв" },
      { en: "ant", bg: "mravka", cyr: "мравка" },
      { en: "fly", bg: "muha", cyr: "муха" },
      { en: "mosquito", bg: "komar", cyr: "комар" },
      { en: "worm", bg: "chervey", cyr: "червей" },
      { en: "whale", bg: "kit", cyr: "кит" },
      { en: "octopus", bg: "oktopod", cyr: "октопод" },
      { en: "seal", bg: "tyulen", cyr: "тюлен" },
      { en: "jellyfish", bg: "meduza", cyr: "медуза" },
      { en: "lizard", bg: "gushter", cyr: "гущер" },
      { en: "camel", bg: "kamila", cyr: "камила" },
      { en: "squirrel", bg: "kateritsa", cyr: "катерица" },
      { en: "hedgehog", bg: "taralezh", cyr: "таралеж" },
      { en: "bat", bg: "prilep", cyr: "прилеп" },
      { en: "crow", bg: "vrana", cyr: "врана" },
    ],
  },
  {
    id: "computers",
    name: "Computers & coding",
    emoji: "💻",
    hue: 204,
    words: [
      { en: "code", bg: "kod", cyr: "код" },
      { en: "program", bg: "programa", cyr: "програма" },
      { en: "software", bg: "softuer", cyr: "софтуер" },
      { en: "hardware", bg: "harduer", cyr: "хардуер" },
      { en: "data", bg: "danni", cyr: "данни" },
      { en: "bug", bg: "greshka", cyr: "грешка" },
      { en: "function", bg: "funktsiya", cyr: "функция" },
      { en: "variable", bg: "promenliva", cyr: "променлива" },
      { en: "folder", bg: "papka", cyr: "папка" },
      { en: "server", bg: "sarvar", cyr: "сървър" },
      { en: "database", bg: "baza danni", cyr: "база данни" },
      { en: "website", bg: "sayt", cyr: "сайт" },
      { en: "browser", bg: "brauzar", cyr: "браузър" },
      { en: "to save", bg: "zapazvam", cyr: "запазвам" },
      { en: "to delete", bg: "iztrivam", cyr: "изтривам" },
      { en: "to copy", bg: "kopiram", cyr: "копирам" },
      { en: "to paste", bg: "postavyam", cyr: "поставям" },
      { en: "memory", bg: "pamet", cyr: "памет" },
      { en: "key", bg: "klavish", cyr: "клавиш" },
      { en: "update", bg: "aktualizatsiya", cyr: "актуализация" },
      { en: "to install", bg: "instaliram", cyr: "инсталирам" },
      { en: "user", bg: "potrebitel", cyr: "потребител" },
      { en: "file", bg: "fayl", cyr: "файл" },
      { en: "screen", bg: "ekran", cyr: "екран" },
      { en: "network", bg: "mrezha", cyr: "мрежа" },
      { en: "cloud", bg: "oblak", cyr: "облак" },
    ],
  },
  {
    id: "communication",
    name: "Talking & communication",
    emoji: "🗣️",
    hue: 280,
    words: [
      { en: "to say", bg: "kazvam", cyr: "казвам" },
      { en: "to tell", bg: "razkazvam", cyr: "разказвам" },
      { en: "to talk", bg: "razgovaryam", cyr: "разговарям" },
      { en: "to explain", bg: "obyasnyavam", cyr: "обяснявам" },
      { en: "to repeat", bg: "povtaryam", cyr: "повтарям" },
      { en: "to promise", bg: "obeshtavam", cyr: "обещавам" },
      { en: "to lie", bg: "lazha", cyr: "лъжа" },
      { en: "to agree", bg: "saglasyavam se", cyr: "съгласявам се" },
      { en: "to argue", bg: "sporya", cyr: "споря" },
      { en: "to discuss", bg: "obsazhdam", cyr: "обсъждам" },
      { en: "to mean", bg: "oznachavam", cyr: "означавам" },
      { en: "to whisper", bg: "shepna", cyr: "шепна" },
      { en: "to shout", bg: "vikam", cyr: "викам" },
      { en: "conversation", bg: "razgovor", cyr: "разговор" },
      { en: "to greet", bg: "pozdravyavam", cyr: "поздравявам" },
      { en: "to apologize", bg: "izvinyavam se", cyr: "извинявам се" },
      { en: "to describe", bg: "opisvam", cyr: "описвам" },
      { en: "to translate", bg: "prevezhdam", cyr: "превеждам" },
      { en: "to ask", bg: "pitam", cyr: "питам" },
      { en: "to answer", bg: "otgovaryam", cyr: "отговарям" },
      { en: "to call", bg: "obazhdam se", cyr: "обаждам се" },
      { en: "word", bg: "duma", cyr: "дума" },
      { en: "question", bg: "vapros", cyr: "въпрос" },
      { en: "to thank", bg: "blagodarya", cyr: "благодаря" },
      { en: "to invite", bg: "kanya", cyr: "каня" },
      { en: "to read aloud", bg: "cheta na glas", cyr: "чета на глас" },
    ],
  },
  {
    id: "quantities",
    name: "Quantities & containers",
    emoji: "📦",
    hue: 42,
    words: [
      { en: "a lot", bg: "mnogo", cyr: "много" },
      { en: "a few", bg: "nyakolko", cyr: "няколко" },
      { en: "some", bg: "nyakoi", cyr: "някои" },
      { en: "piece", bg: "parche", cyr: "парче" },
      { en: "part", bg: "chast", cyr: "част" },
      { en: "pair", bg: "chift", cyr: "чифт" },
      { en: "dozen", bg: "duzina", cyr: "дузина" },
      { en: "handful", bg: "shepa", cyr: "шепа" },
      { en: "slice", bg: "filiya", cyr: "филия" },
      { en: "kilogram", bg: "kilogram", cyr: "килограм" },
      { en: "gram", bg: "gram", cyr: "грам" },
      { en: "liter", bg: "litar", cyr: "литър" },
      { en: "meter", bg: "metar", cyr: "метър" },
      { en: "centimeter", bg: "santimetar", cyr: "сантиметър" },
      { en: "weight", bg: "teglo", cyr: "тегло" },
      { en: "amount", bg: "kolichestvo", cyr: "количество" },
      { en: "half", bg: "polovina", cyr: "половина" },
      { en: "double", bg: "dvoyno", cyr: "двойно" },
      { en: "single", bg: "edinichno", cyr: "единично" },
      { en: "total", bg: "obshto", cyr: "общо" },
      { en: "box", bg: "kutiya", cyr: "кутия" },
      { en: "bottle", bg: "butilka", cyr: "бутилка" },
      { en: "bag", bg: "torba", cyr: "торба" },
      { en: "cup", bg: "chasha", cyr: "чаша" },
      { en: "enough", bg: "dostatachno", cyr: "достатъчно" },
      { en: "full", bg: "palen", cyr: "пълен" },
    ],
  },
  {
    id: "senses",
    name: "Senses & perception",
    emoji: "👁️",
    hue: 310,
    words: [
      { en: "to hear", bg: "chuvam", cyr: "чувам" },
      { en: "to smell", bg: "mirisha", cyr: "мириша" },
      { en: "to taste", bg: "vkusvam", cyr: "вкусвам" },
      { en: "to touch", bg: "dokosvam", cyr: "докосвам" },
      { en: "to look", bg: "gledam", cyr: "гледам" },
      { en: "to listen", bg: "slusham", cyr: "слушам" },
      { en: "to watch", bg: "nablyudavam", cyr: "наблюдавам" },
      { en: "to notice", bg: "zabelyazvam", cyr: "забелязвам" },
      { en: "sight", bg: "zrenie", cyr: "зрение" },
      { en: "hearing", bg: "sluh", cyr: "слух" },
      { en: "smell", bg: "obonyanie", cyr: "обоняние" },
      { en: "taste", bg: "vkus", cyr: "вкус" },
      { en: "touch", bg: "dopir", cyr: "допир" },
      { en: "sound", bg: "zvuk", cyr: "звук" },
      { en: "noise", bg: "shum", cyr: "шум" },
      { en: "silence", bg: "tishina", cyr: "тишина" },
      { en: "bright", bg: "svetal", cyr: "светъл" },
      { en: "loud", bg: "silen", cyr: "силен" },
      { en: "soft", bg: "mek", cyr: "мек" },
      { en: "hard", bg: "tvard", cyr: "твърд" },
      { en: "smooth", bg: "gladak", cyr: "гладък" },
      { en: "rough", bg: "grapav", cyr: "грапав" },
      { en: "sweet", bg: "sladak", cyr: "сладък" },
      { en: "bitter", bg: "gorchiv", cyr: "горчив" },
      { en: "to feel", bg: "useshtam", cyr: "усещам" },
      { en: "to see", bg: "vizhdam", cyr: "виждам" },
    ],
  },
  {
    id: "signs",
    name: "Signs & public places",
    emoji: "🚸",
    hue: 220,
    words: [
      { en: "entrance", bg: "vhod", cyr: "вход" },
      { en: "exit", bg: "izhod", cyr: "изход" },
      { en: "open", bg: "otvoreno", cyr: "отворено" },
      { en: "closed", bg: "zatvoreno", cyr: "затворено" },
      { en: "push", bg: "butni", cyr: "бутни" },
      { en: "pull", bg: "drapni", cyr: "дръпни" },
      { en: "danger", bg: "opasnost", cyr: "опасност" },
      { en: "warning", bg: "preduprezhdenie", cyr: "предупреждение" },
      { en: "forbidden", bg: "zabraneno", cyr: "забранено" },
      { en: "attention", bg: "vnimanie", cyr: "внимание" },
      { en: "information", bg: "informatsiya", cyr: "информация" },
      { en: "toilet", bg: "toaletna", cyr: "тоалетна" },
      { en: "emergency", bg: "speshen sluchay", cyr: "спешен случай" },
      { en: "police", bg: "politsiya", cyr: "полиция" },
      { en: "hospital", bg: "bolnitsa", cyr: "болница" },
      { en: "stop", bg: "stop", cyr: "стоп" },
      { en: "free", bg: "svoboden", cyr: "свободен" },
      { en: "occupied", bg: "zaet", cyr: "зает" },
      { en: "waiting room", bg: "chakalnya", cyr: "чакалня" },
      { en: "ticket office", bg: "kasa", cyr: "каса" },
      { en: "help desk", bg: "spravki", cyr: "справки" },
      { en: "elevator", bg: "asansyor", cyr: "асансьор" },
      { en: "floor", bg: "etazh", cyr: "етаж" },
      { en: "map", bg: "karta", cyr: "карта" },
      { en: "no entry", bg: "vlizaneto zabraneno", cyr: "влизането забранено" },
      { en: "first aid", bg: "parva pomosht", cyr: "първа помощ" },
    ],
  },
  {
    id: "adjectives2",
    name: "More adjectives",
    emoji: "🏷️",
    hue: 88,
    words: [
      { en: "correct", bg: "pravilen", cyr: "правилен" },
      { en: "wrong", bg: "greshen", cyr: "грешен" },
      { en: "possible", bg: "vazmozhen", cyr: "възможен" },
      { en: "impossible", bg: "nevazmozhen", cyr: "невъзможен" },
      { en: "ready", bg: "gotov", cyr: "готов" },
      { en: "busy", bg: "zaet", cyr: "зает" },
      { en: "different", bg: "razlichen", cyr: "различен" },
      { en: "same", bg: "edinakav", cyr: "еднакъв" },
      { en: "similar", bg: "podoben", cyr: "подобен" },
      { en: "real", bg: "istinski", cyr: "истински" },
      { en: "false", bg: "falshiv", cyr: "фалшив" },
      { en: "normal", bg: "normalen", cyr: "нормален" },
      { en: "strange", bg: "stranen", cyr: "странен" },
      { en: "famous", bg: "izvesten", cyr: "известен" },
      { en: "dangerous", bg: "opasen", cyr: "опасен" },
      { en: "safe", bg: "bezopasen", cyr: "безопасен" },
      { en: "simple", bg: "prost", cyr: "прост" },
      { en: "complicated", bg: "slozhen", cyr: "сложен" },
      { en: "usual", bg: "obichaen", cyr: "обичаен" },
      { en: "modern", bg: "moderen", cyr: "модерен" },
      { en: "ancient", bg: "dreven", cyr: "древен" },
      { en: "main", bg: "glaven", cyr: "главен" },
      { en: "whole", bg: "tsyal", cyr: "цял" },
      { en: "broken", bg: "schupen", cyr: "счупен" },
      { en: "alive", bg: "zhiv", cyr: "жив" },
      { en: "dead", bg: "martav", cyr: "мъртъв" },
    ],
  },
  {
    id: "verbs3",
    name: "Verbs of mind & will",
    emoji: "💭",
    hue: 158,
    words: [
      { en: "to decide", bg: "reshavam", cyr: "решавам" },
      { en: "to try", bg: "opitvam se", cyr: "опитвам се" },
      { en: "to wish", bg: "zhelaya", cyr: "желая" },
      { en: "to prefer", bg: "predpochitam", cyr: "предпочитам" },
      { en: "to expect", bg: "ochakvam", cyr: "очаквам" },
      { en: "to imagine", bg: "predstavyam si", cyr: "представям си" },
      { en: "to compare", bg: "sravnyavam", cyr: "сравнявам" },
      { en: "to enjoy", bg: "naslazhdavam se", cyr: "наслаждавам се" },
      { en: "to suffer", bg: "stradam", cyr: "страдам" },
      { en: "to worry", bg: "pritesnyavam se", cyr: "притеснявам се" },
      { en: "to dream", bg: "mechtaya", cyr: "мечтая" },
      { en: "to plan", bg: "planiram", cyr: "планирам" },
      { en: "to allow", bg: "pozvolyavam", cyr: "позволявам" },
      { en: "to forbid", bg: "zabranyavam", cyr: "забранявам" },
      { en: "to accept", bg: "priemam", cyr: "приемам" },
      { en: "to refuse", bg: "otkazvam", cyr: "отказвам" },
      { en: "to count", bg: "broya", cyr: "броя" },
      { en: "to measure", bg: "izmervam", cyr: "измервам" },
      { en: "to fill", bg: "palnya", cyr: "пълня" },
      { en: "to empty", bg: "izprazvam", cyr: "изпразвам" },
      { en: "to throw", bg: "hvarlyam", cyr: "хвърлям" },
      { en: "to catch", bg: "hvashtam", cyr: "хващам" },
      { en: "to pull", bg: "darpam", cyr: "дърпам" },
      { en: "to push", bg: "butam", cyr: "бутам" },
      { en: "to weigh", bg: "teglya", cyr: "тегля" },
      { en: "to rescue", bg: "spasyavam", cyr: "спасявам" },
    ],
  },
  {
    id: "actions",
    name: "Body actions",
    emoji: "🙆",
    hue: 12,
    words: [
      { en: "to step", bg: "stapvam", cyr: "стъпвам" },
      { en: "to stand", bg: "stoya", cyr: "стоя" },
      { en: "to sit", bg: "sedya", cyr: "седя" },
      { en: "to lie down", bg: "lyagam", cyr: "лягам" },
      { en: "to kneel", bg: "klyakam", cyr: "клякам" },
      { en: "to bend", bg: "navezhdam se", cyr: "навеждам се" },
      { en: "to stretch", bg: "protyagam se", cyr: "протягам се" },
      { en: "to turn", bg: "obrashtam se", cyr: "обръщам се" },
      { en: "to climb", bg: "katerya se", cyr: "катеря се" },
      { en: "to crawl", bg: "palzya", cyr: "пълзя" },
      { en: "to kick", bg: "ritam", cyr: "ритам" },
      { en: "to lift", bg: "vdigam", cyr: "вдигам" },
      { en: "to drop", bg: "izpuskam", cyr: "изпускам" },
      { en: "to hold", bg: "darzha", cyr: "държа" },
      { en: "to shake", bg: "klatya", cyr: "клатя" },
      { en: "to wave", bg: "maham", cyr: "махам" },
      { en: "to point", bg: "socha", cyr: "соча" },
      { en: "to nod", bg: "kimam", cyr: "кимам" },
      { en: "to clap", bg: "plyaskam", cyr: "пляскам" },
      { en: "to blink", bg: "migam", cyr: "мигам" },
      { en: "to yawn", bg: "prozyavam se", cyr: "прозявам се" },
      { en: "to sneeze", bg: "kiham", cyr: "кихам" },
      { en: "to bite", bg: "hapya", cyr: "хапя" },
      { en: "to chew", bg: "davcha", cyr: "дъвча" },
      { en: "to hug", bg: "pregrashtam", cyr: "прегръщам" },
      { en: "to kiss", bg: "tseluvam", cyr: "целувам" },
    ],
  },
];

export function getTheme(id: string): Theme | undefined {
  return THEMES.find((t) => t.id === id);
}

// Normalize for comparison: lowercase, drop punctuation, collapse whitespace.
export function normalize(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}

// True if `input` matches `expected`. A "/" in expected marks alternatives,
// so "hand / arm" accepts either "hand" or "arm".
export function matches(input: string, expected: string): boolean {
  const got = normalize(input);
  if (!got) return false;
  const candidates = expected.split("/").map(normalize).filter(Boolean);
  candidates.push(normalize(expected));
  return candidates.includes(got);
}

// Weighted random index. `weights[i]` is the relative chance of picking i;
// a weight of 0 excludes that entry (used to avoid immediate repeats and to
// favour words the player keeps missing). `rng` is injectable for testing.
export function pickIndex(weights: number[], rng: () => number = Math.random): number {
  const total = weights.reduce((a, b) => a + (b > 0 ? b : 0), 0);
  if (total <= 0) return 0;
  let r = rng() * total;
  for (let i = 0; i < weights.length; i++) {
    if (weights[i] > 0) {
      r -= weights[i];
      if (r < 0) return i;
    }
  }
  // Fallback: last entry with a positive weight.
  for (let i = weights.length - 1; i >= 0; i--) if (weights[i] > 0) return i;
  return 0;
}
