// Bulgarian vocabulary, transliterated to Latin letters.
// `bg` is the accepted answer (Latin), `cyr` is the Cyrillic (shown + spoken).
// A "/" in a value marks alternative accepted answers (e.g. "hand / arm").

export type Word = {
  en: string;
  bg: string; // Bulgarian written in Latin letters
  cyr: string; // Cyrillic, shown as a learning aid and used for speech
};

export type Theme = {
  id: string;
  name: string;
  emoji: string;
  hue: number; // base hue used for the theme's accent gradient
  words: Word[];
};

export const THEMES: Theme[] = [
  {
    id: "everyday",
    name: "Everyday phrases",
    emoji: "💬",
    hue: 265,
    words: [
      { en: "hello", bg: "zdravey", cyr: "здравей" },
      { en: "hi", bg: "zdrasti", cyr: "здрасти" },
      { en: "goodbye", bg: "dovizhdane", cyr: "довиждане" },
      { en: "thank you", bg: "blagodarya", cyr: "благодаря" },
      { en: "please", bg: "molya", cyr: "моля" },
      { en: "yes", bg: "da", cyr: "да" },
      { en: "no", bg: "ne", cyr: "не" },
      { en: "good morning", bg: "dobro utro", cyr: "добро утро" },
      { en: "good afternoon", bg: "dobar den", cyr: "добър ден" },
      { en: "good evening", bg: "dobar vecher", cyr: "добър вечер" },
      { en: "good night", bg: "leka nosht", cyr: "лека нощ" },
      { en: "how are you", bg: "kak si", cyr: "как си" },
      { en: "I'm fine", bg: "dobre sam", cyr: "добре съм" },
      { en: "excuse me", bg: "izvinete", cyr: "извинете" },
      { en: "sorry", bg: "sazhalyavam", cyr: "съжалявам" },
      { en: "behind us", bg: "zad nas", cyr: "зад нас" },
      { en: "I love you", bg: "obicham te", cyr: "обичам те" },
      { en: "what's your name", bg: "kak se kazvash", cyr: "как се казваш" },
      { en: "my name is", bg: "kazvam se", cyr: "казвам се" },
      { en: "where", bg: "kade", cyr: "къде" },
      { en: "when", bg: "koga", cyr: "кога" },
      { en: "why", bg: "zashto", cyr: "защо" },
      { en: "who", bg: "koy", cyr: "кой" },
      { en: "how", bg: "kak", cyr: "как" },
      { en: "how much", bg: "kolko", cyr: "колко" },
      { en: "now", bg: "sega", cyr: "сега" },
      { en: "of course", bg: "razbira se", cyr: "разбира се" },
      { en: "I don't know", bg: "ne znam", cyr: "не знам" },
      { en: "I don't understand", bg: "ne razbiram", cyr: "не разбирам" },
      { en: "help", bg: "pomosht", cyr: "помощ" },
      { en: "cheers", bg: "nazdrave", cyr: "наздраве" },
    ],
  },
  {
    id: "food",
    name: "Food & drink",
    emoji: "🍽️",
    hue: 12,
    words: [
      { en: "water", bg: "voda", cyr: "вода" },
      { en: "bread", bg: "hlyab", cyr: "хляб" },
      { en: "coffee", bg: "kafe", cyr: "кафе" },
      { en: "beer", bg: "bira", cyr: "бира" },
      { en: "wine", bg: "vino", cyr: "вино" },
      { en: "milk", bg: "mlyako", cyr: "мляко" },
      { en: "cheese", bg: "sirene", cyr: "сирене" },
      { en: "yellow cheese", bg: "kashkaval", cyr: "кашкавал" },
      { en: "meat", bg: "meso", cyr: "месо" },
      { en: "chicken", bg: "pile", cyr: "пиле" },
      { en: "fish", bg: "riba", cyr: "риба" },
      { en: "egg", bg: "yaytse", cyr: "яйце" },
      { en: "apple", bg: "yabalka", cyr: "ябълка" },
      { en: "banana", bg: "banan", cyr: "банан" },
      { en: "tomato", bg: "domat", cyr: "домат" },
      { en: "cucumber", bg: "krastavitsa", cyr: "краставица" },
      { en: "potato", bg: "kartof", cyr: "картоф" },
      { en: "soup", bg: "supa", cyr: "супа" },
      { en: "salad", bg: "salata", cyr: "салата" },
      { en: "sugar", bg: "zahar", cyr: "захар" },
      { en: "salt", bg: "sol", cyr: "сол" },
      { en: "pepper", bg: "piper", cyr: "пипер" },
      { en: "tea", bg: "chay", cyr: "чай" },
      { en: "juice", bg: "sok", cyr: "сок" },
      { en: "yogurt", bg: "kiselo mlyako", cyr: "кисело мляко" },
      { en: "breakfast", bg: "zakuska", cyr: "закуска" },
      { en: "lunch", bg: "obyad", cyr: "обяд" },
      { en: "dinner", bg: "vecherya", cyr: "вечеря" },
      { en: "the bill", bg: "smetkata", cyr: "сметката" },
      { en: "delicious", bg: "vkusno", cyr: "вкусно" },
      { en: "spicy", bg: "lyuto", cyr: "люто" },
    ],
  },
  {
    id: "travel",
    name: "Travel & places",
    emoji: "✈️",
    hue: 192,
    words: [
      { en: "airport", bg: "letishte", cyr: "летище" },
      { en: "train", bg: "vlak", cyr: "влак" },
      { en: "bus", bg: "avtobus", cyr: "автобус" },
      { en: "car", bg: "kola", cyr: "кола" },
      { en: "taxi", bg: "taksi", cyr: "такси" },
      { en: "ticket", bg: "bilet", cyr: "билет" },
      { en: "hotel", bg: "hotel", cyr: "хотел" },
      { en: "room", bg: "staya", cyr: "стая" },
      { en: "street", bg: "ulitsa", cyr: "улица" },
      { en: "square", bg: "ploshtad", cyr: "площад" },
      { en: "city", bg: "grad", cyr: "град" },
      { en: "village", bg: "selo", cyr: "село" },
      { en: "left", bg: "lyavo", cyr: "ляво" },
      { en: "right", bg: "dyasno", cyr: "дясно" },
      { en: "straight ahead", bg: "napravo", cyr: "направо" },
      { en: "near", bg: "blizo", cyr: "близо" },
      { en: "far", bg: "daleche", cyr: "далече" },
      { en: "map", bg: "karta", cyr: "карта" },
      { en: "beach", bg: "plazh", cyr: "плаж" },
      { en: "sea", bg: "more", cyr: "море" },
      { en: "mountain", bg: "planina", cyr: "планина" },
      { en: "river", bg: "reka", cyr: "река" },
      { en: "forest", bg: "gora", cyr: "гора" },
      { en: "park", bg: "park", cyr: "парк" },
      { en: "church", bg: "tsarkva", cyr: "църква" },
      { en: "museum", bg: "muzey", cyr: "музей" },
      { en: "market", bg: "pazar", cyr: "пазар" },
      { en: "station", bg: "gara", cyr: "гара" },
      { en: "where is", bg: "kade e", cyr: "къде е" },
      { en: "passport", bg: "pasport", cyr: "паспорт" },
      { en: "luggage", bg: "bagazh", cyr: "багаж" },
    ],
  },
  {
    id: "numbers",
    name: "Numbers & time",
    emoji: "🔢",
    hue: 142,
    words: [
      { en: "zero", bg: "nula", cyr: "нула" },
      { en: "one", bg: "edno", cyr: "едно" },
      { en: "two", bg: "dve", cyr: "две" },
      { en: "three", bg: "tri", cyr: "три" },
      { en: "four", bg: "chetiri", cyr: "четири" },
      { en: "five", bg: "pet", cyr: "пет" },
      { en: "six", bg: "shest", cyr: "шест" },
      { en: "seven", bg: "sedem", cyr: "седем" },
      { en: "eight", bg: "osem", cyr: "осем" },
      { en: "nine", bg: "devet", cyr: "девет" },
      { en: "ten", bg: "deset", cyr: "десет" },
      { en: "eleven", bg: "edinadeset", cyr: "единадесет" },
      { en: "twelve", bg: "dvanadeset", cyr: "дванадесет" },
      { en: "twenty", bg: "dvadeset", cyr: "двадесет" },
      { en: "fifty", bg: "petdeset", cyr: "петдесет" },
      { en: "hundred", bg: "sto", cyr: "сто" },
      { en: "thousand", bg: "hilyada", cyr: "хиляда" },
      { en: "today", bg: "dnes", cyr: "днес" },
      { en: "tomorrow", bg: "utre", cyr: "утре" },
      { en: "yesterday", bg: "vchera", cyr: "вчера" },
      { en: "day", bg: "den", cyr: "ден" },
      { en: "week", bg: "sedmitsa", cyr: "седмица" },
      { en: "month", bg: "mesets", cyr: "месец" },
      { en: "year", bg: "godina", cyr: "година" },
      { en: "hour", bg: "chas", cyr: "час" },
      { en: "minute", bg: "minuta", cyr: "минута" },
      { en: "morning", bg: "sutrin", cyr: "сутрин" },
      { en: "evening", bg: "vecher", cyr: "вечер" },
      { en: "Monday", bg: "ponedelnik", cyr: "понеделник" },
      { en: "Friday", bg: "petak", cyr: "петък" },
      { en: "what time is it", bg: "kolko e chasat", cyr: "колко е часът" },
    ],
  },
  {
    id: "family",
    name: "Family & people",
    emoji: "👪",
    hue: 320,
    words: [
      { en: "mother", bg: "mayka", cyr: "майка" },
      { en: "father", bg: "bashta", cyr: "баща" },
      { en: "parents", bg: "roditeli", cyr: "родители" },
      { en: "son", bg: "sin", cyr: "син" },
      { en: "daughter", bg: "dashterya", cyr: "дъщеря" },
      { en: "child", bg: "dete", cyr: "дете" },
      { en: "children", bg: "detsa", cyr: "деца" },
      { en: "brother", bg: "brat", cyr: "брат" },
      { en: "sister", bg: "sestra", cyr: "сестра" },
      { en: "grandmother", bg: "baba", cyr: "баба" },
      { en: "grandfather", bg: "dyado", cyr: "дядо" },
      { en: "husband", bg: "saprug", cyr: "съпруг" },
      { en: "wife", bg: "sapruga", cyr: "съпруга" },
      { en: "friend", bg: "priyatel", cyr: "приятел" },
      { en: "girlfriend", bg: "priyatelka", cyr: "приятелка" },
      { en: "boy", bg: "momche", cyr: "момче" },
      { en: "girl", bg: "momiche", cyr: "момиче" },
      { en: "man", bg: "mazh", cyr: "мъж" },
      { en: "woman", bg: "zhena", cyr: "жена" },
      { en: "people", bg: "hora", cyr: "хора" },
      { en: "family", bg: "semeystvo", cyr: "семейство" },
      { en: "name", bg: "ime", cyr: "име" },
      { en: "neighbor", bg: "sased", cyr: "съсед" },
      { en: "guest", bg: "gost", cyr: "гост" },
    ],
  },
  {
    id: "body",
    name: "Body & health",
    emoji: "🩺",
    hue: 0,
    words: [
      { en: "head", bg: "glava", cyr: "глава" },
      { en: "hair", bg: "kosa", cyr: "коса" },
      { en: "eye", bg: "oko", cyr: "око" },
      { en: "eyes", bg: "ochi", cyr: "очи" },
      { en: "ear", bg: "uho", cyr: "ухо" },
      { en: "nose", bg: "nos", cyr: "нос" },
      { en: "mouth", bg: "usta", cyr: "уста" },
      { en: "tooth", bg: "zab", cyr: "зъб" },
      { en: "tongue", bg: "ezik", cyr: "език" },
      { en: "neck", bg: "vrat", cyr: "врат" },
      { en: "hand / arm", bg: "raka", cyr: "ръка" },
      { en: "finger", bg: "prast", cyr: "пръст" },
      { en: "leg / foot", bg: "krak", cyr: "крак" },
      { en: "heart", bg: "sartse", cyr: "сърце" },
      { en: "stomach", bg: "stomah", cyr: "стомах" },
      { en: "back", bg: "garb", cyr: "гръб" },
      { en: "blood", bg: "krav", cyr: "кръв" },
      { en: "skin", bg: "kozha", cyr: "кожа" },
      { en: "doctor", bg: "lekar", cyr: "лекар" },
      { en: "pharmacy", bg: "apteka", cyr: "аптека" },
      { en: "medicine", bg: "lekarstvo", cyr: "лекарство" },
      { en: "pain", bg: "bolka", cyr: "болка" },
      { en: "sick", bg: "bolen", cyr: "болен" },
      { en: "healthy", bg: "zdrav", cyr: "здрав" },
      { en: "hospital", bg: "bolnitsa", cyr: "болница" },
    ],
  },
  {
    id: "weather",
    name: "Weather & nature",
    emoji: "🌦️",
    hue: 205,
    words: [
      { en: "weather", bg: "vreme", cyr: "време" },
      { en: "sun", bg: "slantse", cyr: "слънце" },
      { en: "moon", bg: "luna", cyr: "луна" },
      { en: "star", bg: "zvezda", cyr: "звезда" },
      { en: "sky", bg: "nebe", cyr: "небе" },
      { en: "cloud", bg: "oblak", cyr: "облак" },
      { en: "rain", bg: "dazhd", cyr: "дъжд" },
      { en: "snow", bg: "snyag", cyr: "сняг" },
      { en: "wind", bg: "vyatar", cyr: "вятър" },
      { en: "storm", bg: "burya", cyr: "буря" },
      { en: "fog", bg: "magla", cyr: "мъгла" },
      { en: "hot", bg: "goreshto", cyr: "горещо" },
      { en: "cold", bg: "studeno", cyr: "студено" },
      { en: "warm", bg: "toplo", cyr: "топло" },
      { en: "ice", bg: "led", cyr: "лед" },
      { en: "fire", bg: "ogan", cyr: "огън" },
      { en: "earth", bg: "zemya", cyr: "земя" },
      { en: "tree", bg: "darvo", cyr: "дърво" },
      { en: "flower", bg: "tsvete", cyr: "цвете" },
      { en: "grass", bg: "treva", cyr: "трева" },
      { en: "animal", bg: "zhivotno", cyr: "животно" },
      { en: "spring", bg: "prolet", cyr: "пролет" },
      { en: "summer", bg: "lyato", cyr: "лято" },
      { en: "autumn", bg: "esen", cyr: "есен" },
      { en: "winter", bg: "zima", cyr: "зима" },
    ],
  },
  {
    id: "shopping",
    name: "Shopping & money",
    emoji: "🛍️",
    hue: 45,
    words: [
      { en: "shop", bg: "magazin", cyr: "магазин" },
      { en: "market", bg: "pazar", cyr: "пазар" },
      { en: "money", bg: "pari", cyr: "пари" },
      { en: "price", bg: "tsena", cyr: "цена" },
      { en: "cheap", bg: "evtino", cyr: "евтино" },
      { en: "expensive", bg: "skapo", cyr: "скъпо" },
      { en: "how much does it cost", bg: "kolko struva", cyr: "колко струва" },
      { en: "to buy", bg: "kupuvam", cyr: "купувам" },
      { en: "to pay", bg: "plashtam", cyr: "плащам" },
      { en: "to sell", bg: "prodavam", cyr: "продавам" },
      { en: "cash", bg: "v broy", cyr: "в брой" },
      { en: "receipt", bg: "kasova belezhka", cyr: "касова бележка" },
      { en: "bag", bg: "torba", cyr: "торба" },
      { en: "clothes", bg: "drehi", cyr: "дрехи" },
      { en: "shoes", bg: "obuvki", cyr: "обувки" },
      { en: "shirt", bg: "riza", cyr: "риза" },
      { en: "trousers", bg: "pantalon", cyr: "панталон" },
      { en: "dress", bg: "roklya", cyr: "рокля" },
      { en: "hat", bg: "shapka", cyr: "шапка" },
      { en: "size", bg: "razmer", cyr: "размер" },
      { en: "open", bg: "otvoreno", cyr: "отворено" },
      { en: "closed", bg: "zatvoreno", cyr: "затворено" },
      { en: "sale", bg: "namalenie", cyr: "намаление" },
      { en: "gift", bg: "podarak", cyr: "подарък" },
    ],
  },
  {
    id: "verbs",
    name: "Common verbs",
    emoji: "🏃",
    hue: 160,
    words: [
      { en: "to be", bg: "sam", cyr: "съм" },
      { en: "to have", bg: "imam", cyr: "имам" },
      { en: "to want", bg: "iskam", cyr: "искам" },
      { en: "to be able", bg: "moga", cyr: "мога" },
      { en: "to go", bg: "otivam", cyr: "отивам" },
      { en: "to come", bg: "idvam", cyr: "идвам" },
      { en: "to eat", bg: "yam", cyr: "ям" },
      { en: "to drink", bg: "piya", cyr: "пия" },
      { en: "to sleep", bg: "spya", cyr: "спя" },
      { en: "to speak", bg: "govorya", cyr: "говоря" },
      { en: "to know", bg: "znam", cyr: "знам" },
      { en: "to see", bg: "vizhdam", cyr: "виждам" },
      { en: "to make / do", bg: "pravya", cyr: "правя" },
      { en: "to give", bg: "davam", cyr: "давам" },
      { en: "to take", bg: "vzemam", cyr: "взимам" },
      { en: "to read", bg: "cheta", cyr: "чета" },
      { en: "to write", bg: "pisha", cyr: "пиша" },
      { en: "to work", bg: "rabotya", cyr: "работя" },
      { en: "to live", bg: "zhiveya", cyr: "живея" },
      { en: "to love", bg: "obicham", cyr: "обичам" },
      { en: "to think", bg: "mislya", cyr: "мисля" },
      { en: "to open", bg: "otvaryam", cyr: "отварям" },
      { en: "to wait", bg: "chakam", cyr: "чакам" },
      { en: "to walk", bg: "varvya", cyr: "вървя" },
      { en: "to run", bg: "byagam", cyr: "бягам" },
      { en: "to help", bg: "pomagam", cyr: "помагам" },
    ],
  },
];

export function getTheme(id: string): Theme | undefined {
  return THEMES.find((t) => t.id === id);
}

// Normalize for comparison: lowercase, drop punctuation, collapse whitespace.
export function normalize(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}

// True if `input` matches `expected`. A "/" in expected marks alternatives,
// so "hand / arm" accepts either "hand" or "arm".
export function matches(input: string, expected: string): boolean {
  const got = normalize(input);
  if (!got) return false;
  const candidates = expected.split("/").map(normalize).filter(Boolean);
  candidates.push(normalize(expected));
  return candidates.includes(got);
}
