// Generates public/sw.js after `next build`, precaching the build's hashed
// static assets so the app loads fully offline on the very first visit.
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const staticDir = join(root, ".next", "static");

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

let assets = [];
try {
  assets = walk(staticDir).map(
    (p) => "/_next/static/" + relative(staticDir, p).split("\\").join("/"),
  );
} catch {
  console.warn("gen-sw: no .next/static found — run `next build` first");
}

const precache = [
  "/",
  "/manifest.webmanifest",
  "/icon-192.png",
  "/icon-512.png",
  "/apple-touch-icon.png",
  ...assets,
];

const version = createHash("sha1")
  .update(precache.join("|"))
  .digest("hex")
  .slice(0, 10);

const sw = `// AUTO-GENERATED by scripts/gen-sw.mjs — do not edit.
const CACHE = "bulgapop-${version}";
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE).then((cache) =>
      Promise.allSettled(
        PRECACHE.map((url) =>
          fetch(new Request(url, { cache: "reload" }))
            .then((res) => (res.ok ? cache.put(url, res) : null))
            .catch(() => null),
        ),
      ),
    ),
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // App navigations: network-first, fall back to the cached app shell.
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put("/", copy));
          return res;
        })
        .catch(() =>
          caches.match("/", { ignoreSearch: true }).then((r) => r || caches.match(req)),
        ),
    );
    return;
  }

  // Everything else same-origin: cache-first, then network (and cache it).
  e.respondWith(
    caches.match(req).then(
      (cached) =>
        cached ||
        fetch(req)
          .then((res) => {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
            return res;
          })
          .catch(() => cached),
    ),
  );
});
`;

writeFileSync(join(root, "public", "sw.js"), sw);
console.log(`gen-sw: wrote public/sw.js (${precache.length} entries, cache bulgapop-${version})`);
